if (typeof window.registerSubject === 'function') {
    window.registerSubject('Anatomy', [
        { q: "Extraction of which tooth puts Lingual Nerve at risk?", a: "Lower third molar", options: ["Upper first molar", "Lower third molar", "Upper canine", "Lower first molar"] },
        { q: "Muscle elevating upper eyelid supplied by CN III?", a: "Levator Palpebrae Superioris", options: ["Orbicularis oculi", "Levator Palpebrae Superioris", "Superior Rectus", "Frontalis"] },
        { q: "Posterior tibial artery pulsation is felt?", a: "Behind medial malleolus", options: ["Anterior to lateral malleolus", "Behind medial malleolus", "Dorsum of foot", "Popliteal fossa"] },
        { q: "Chorda tympani nerve injury affects?", a: "Taste from anterior 2/3 of tongue", options: ["Vision", "Smell", "Taste from anterior 2/3 of tongue", "Pain from posterior 1/3"] },
        { q: "Down and Out eye position is seen in?", a: "Oculomotor (CN III) palsy", options: ["Abducens palsy", "Trochlear palsy", "Oculomotor (CN III) palsy", "Optic nerve lesion"] },
        { q: "Artery passing through Cavernous Sinus?", a: "Internal Carotid Artery", options: ["External Carotid", "Internal Carotid Artery", "Middle Meningeal", "Basilar"] },
        { q: "Nerve passing through Cavernous Sinus (with ICA)?", a: "Abducens (CN VI)", options: ["Optic", "Abducens (CN VI)", "Facial", "Vagus"] },
        { q: "Safety muscle of tongue?", a: "Genioglossus", options: ["Hyoglossus", "Styloglossus", "Genioglossus", "Palatoglossus"] },
        { q: "Winged scapula is due to injury of?", a: "Long Thoracic Nerve (Serratus Anterior)", options: ["Axillary nerve", "Long Thoracic Nerve", "Suprascapular nerve", "Radial nerve"] },
        { q: "Foot drop is caused by injury to?", a: "Common Peroneal Nerve", options: ["Tibial nerve", "Common Peroneal Nerve", "Femoral nerve", "Obturator nerve"] },
        { q: "Wrist drop is caused by injury to?", a: "Radial Nerve", options: ["Ulnar nerve", "Median nerve", "Radial Nerve", "Axillary nerve"] },
        { q: "Claw hand involves?", a: "Ulnar Nerve", options: ["Radial nerve", "Ulnar Nerve", "Median nerve", "Musculocutaneous nerve"] },
        { q: "Erb's point involves roots?", a: "C5, C6", options: ["C5, C6", "C8, T1", "C7", "T2"] },
        { q: "Klumpke's paralysis involves roots?", a: "C8, T1", options: ["C5, C6", "C8, T1", "C6, C7", "C1, C2"] },
        { q: "Most common site of ectopic pregnancy?", a: "Ampulla of fallopian tube", options: ["Isthmus", "Ampulla", "Infundibulum", "Ovary"] },
        { q: "Sperm maturation occurs in?", a: "Epididymis", options: ["Seminiferous tubules", "Epididymis", "Vas deferens", "Seminal vesicle"] },
        { q: "Transitional epithelium is found in?", a: "Urinary Bladder / Ureter", options: ["Skin", "Urinary Bladder / Ureter", "Trachea", "Esophagus"] },
        { q: "Pouch of Douglas is located between?", a: "Rectum and Uterus", options: ["Bladder and Uterus", "Rectum and Uterus", "Rectum and Bladder", "None"] },
        { q: "Appendix is attached to?", a: "Cecum", options: ["Ileum", "Cecum", "Sigmoid", "Duodenum"] },
        { q: "Portal vein is formed by union of?", a: "Splenic vein and Superior Mesenteric Vein", options: ["Splenic and IMV", "Splenic vein and Superior Mesenteric Vein", "Hepatic and Cystic", "Renal and Gonadal"] },
        { q: "Coronary arteries arise from?", a: "Ascending Aorta", options: ["Arch of Aorta", "Ascending Aorta", "Descending Aorta", "Pulmonary Trunk"] },
        { q: "Great Saphenous Vein drains into?", a: "Femoral Vein", options: ["Popliteal Vein", "Femoral Vein", "Iliac Vein", "Tibial Vein"] },
        { q: "Sciatic nerve divides into?", a: "Tibial and Common Peroneal Nerve", options: ["Femoral and Obturator", "Tibial and Common Peroneal Nerve", "Ulnar and Median", "Radial and Axillary"] },
        { q: "Fontanelles usually close by?", a: "18 months (Anterior)", options: ["3 months", "6 months", "18 months", "3 years"] },
        { q: "Broca's area is located in?", a: "Frontal Lobe", options: ["Parietal Lobe", "Temporal Lobe", "Frontal Lobe", "Occipital Lobe"] },
        { q: "Visual cortex is located in?", a: "Occipital Lobe", options: ["Frontal", "Parietal", "Temporal", "Occipital Lobe"] },
        { q: "Auditory area is located in?", a: "Temporal Lobe", options: ["Frontal", "Parietal", "Temporal Lobe", "Occipital"] },
        { q: "Sensory cortex is located in?", a: "Parietal Lobe (Postcentral gyrus)", options: ["Frontal", "Parietal Lobe", "Temporal", "Occipital"] },
        { q: "Motor cortex is located in?", a: "Frontal Lobe (Precentral gyrus)", options: ["Frontal Lobe", "Parietal", "Temporal", "Occipital"] },
        { q: "Diaphragm is supplied by?", a: "Phrenic Nerve (C3, C4, C5)", options: ["Vagus", "Phrenic Nerve", "Intercostal nerves", "Splanchnic nerve"] },
        { q: "Major muscle of respiration?", a: "Diaphragm", options: ["Intercostals", "Diaphragm", "Scalene", "SCM"] },
        { q: "Structure passing through Diaphragm at T10?", a: "Esophagus", options: ["IVC", "Esophagus", "Aorta", "Thoracic duct"] },
        { q: "Structure passing through Diaphragm at T8?", a: "IVC", options: ["Esophagus", "IVC", "Aorta", "Vagus"] },
        { q: "Structure passing through Diaphragm at T12?", a: "Aorta", options: ["IVC", "Esophagus", "Aorta", "Vagus"] },
        { q: "Inguinal canal contains?", a: "Spermatic Cord (Male) / Round Ligament (Female)", options: ["Femoral nerve", "Spermatic Cord / Round Ligament", "Ureter", "Obturator nerve"] },
        { q: "Femoral triangle content lateral to medial?", a: "Nerve, Artery, Vein, Lymphatics (NAVEL)", options: ["Vein, Artery, Nerve", "Nerve, Artery, Vein, Lymphatics", "Artery, Vein, Nerve", "None"] },
        { q: "Rotator cuff muscles (SITS)?", a: "Supraspinatus, Infraspinatus, Teres Minor, Subscapularis", options: ["Supraspinatus, Infraspinatus, Teres Major, Subscapularis", "Supraspinatus, Infraspinatus, Teres Minor, Subscapularis", "Deltoid, Teres Minor, Supraspinatus", "None"] },
        { q: "Carpal Tunnel contains?", a: "Median Nerve and Flexor tendons", options: ["Ulnar nerve", "Median Nerve and Flexor tendons", "Radial nerve", "Palmaris longus"] },
        { q: "Anatomical Snuffbox floor formed by?", a: "Scaphoid", options: ["Lunate", "Scaphoid", "Triquetrum", "Pisiform"] },
        { q: "Content of Anatomical Snuffbox?", a: "Radial Artery", options: ["Ulnar artery", "Radial Artery", "Median nerve", "Ulnar nerve"] },
        { q: "Circle of Willis is formed by?", a: "Internal Carotid and Vertebral/Basilar systems", options: ["External Carotid", "Internal Carotid and Vertebral/Basilar", "Common Carotid", "Subclavian"] },
        { q: "Middle Meningeal Artery enters skull through?", a: "Foramen Spinosum", options: ["Foramen Ovale", "Foramen Spinosum", "Foramen Rotundum", "Foramen Magnum"] },
        { q: "Foramen Ovale transmits?", a: "Mandibular Nerve (V3)", options: ["Maxillary Nerve", "Mandibular Nerve (V3)", "Ophthalmic Nerve", "Middle Meningeal Artery"] },
        { q: "Foramen Rotundum transmits?", a: "Maxillary Nerve (V2)", options: ["Mandibular Nerve", "Maxillary Nerve (V2)", "Ophthalmic Nerve", "Facial Nerve"] },
        { q: "Stylomastoid foramen transmits?", a: "Facial Nerve", options: ["Trigeminal", "Facial Nerve", "Vagus", "Glossopharyngeal"] }
    ]);
}