if (typeof window.registerSubject === 'function') {
    window.registerSubject('Forensic Med', [
        { q: "Question by lawyer to witness 'did you see accused running?'. Disallowed in Direct. Allowed in?", a: "Cross examination (Leading question)", options: ["Direct examination", "Cross examination", "Dying declaration", "Re-direct"] },
        { q: "Inquest in case of Dowry Death is conducted by?", a: "Magistrate", options: ["Police", "Magistrate", "Doctor", "Sarpanch"] },
        { q: "IPC 304A deals with?", a: "Causing death by negligence", options: ["Murder", "Causing death by negligence", "Rape", "Dowry death"] },
        { q: "Punishment for perjury (False evidence) is under?", a: "IPC 193", options: ["IPC 193", "IPC 302", "IPC 375", "IPC 84"] },
        { q: "McNaughton's rule relates to?", a: "Criminal Responsibility (Insanity)", options: ["Civil negligence", "Criminal Responsibility (Insanity)", "Consent", "Witness"] },
        { q: "Dying declaration has value in?", a: "Both Civil and Criminal cases", options: ["Civil only", "Criminal only", "Both Civil and Criminal cases", "None"] },
        { q: "Post mortem lividity (Hypostasis) fixes in?", a: "6-12 hours", options: ["1-2 hours", "6-12 hours", "24 hours", "3 days"] },
        { q: "Rigor Mortis starts in?", a: "1-2 hours", options: ["1-2 hours", "6 hours", "12 hours", "24 hours"] },
        { q: "Pugilistic attitude is seen in?", a: "Burn cases", options: ["Drowning", "Hanging", "Burn cases", "Electrocution"] },
        { q: "Washerwoman's hands are seen in?", a: "Drowning", options: ["Burning", "Drowning", "Strangulation", "Poisoning"] },
        { q: "Cherry red hypostasis is seen in?", a: "Carbon Monoxide poisoning", options: ["Cyanide", "Carbon Monoxide poisoning", "Opium", "Phosphorus"] },
        { q: "Brush burn is a type of?", a: "Abrasion (Graze)", options: ["Contusion", "Laceration", "Abrasion (Graze)", "Incision"] },
        { q: "Choking (gunshot residue) is seen in?", a: "Gunshot wounds (Close range)", options: ["Stab", "Gunshot wounds", "Laceration", "Abrasion"] },
        { q: "Smothering is?", a: "Blockage of external respiratory orifices", options: ["Compression of neck", "Blockage of external respiratory orifices", "Blockage of internal airways", "Pressure on chest"] },
        { q: "Hyoid bone fracture is most common in?", a: "Throttling (Manual Strangulation)", options: ["Hanging", "Ligature strangulation", "Throttling", "Drowning"] },
        { q: "Diatoms test is used for?", a: "Antemortem Drowning", options: ["Burns", "Antemortem Drowning", "Poisoning", "Hanging"] },
        { q: "Gettler's test is for?", a: "Drowning (Chloride in heart)", options: ["Burns", "Drowning", "Hanging", "Gunshot"] },
        { q: "Most common type of fingerprint?", a: "Loop", options: ["Whorl", "Arch", "Loop", "Composite"] },
        { q: "Cephalic Index helps in determination of?", a: "Race", options: ["Sex", "Age", "Race", "Stature"] },
        { q: "Gustafson's method is used for?", a: "Age estimation from teeth", options: ["Sex from pelvis", "Age estimation from teeth", "Stature from femur", "Race from skull"] },
        { q: "IPC 302 deals with?", a: "Punishment for Murder", options: ["Culpable homicide", "Punishment for Murder", "Rape", "Kidnapping"] },
        { q: "IPC 320 deals with?", a: "Grievous Hurt", options: ["Simple hurt", "Grievous Hurt", "Assault", "Torture"] },
        { q: "Potassium permanganate crystals are used for?", a: "Abortion (Abortifacient)", options: ["Suicide", "Abortion", "Homicide", "Staining"] },
        { q: "Lucid interval is seen in?", a: "Extradural Hemorrhage", options: ["Subdural", "Extradural Hemorrhage", "Subarachnoid", "Intracerebral"] },
        { q: "Filigree burns are seen in?", a: "Lightning strike", options: ["Flame burn", "Lightning strike", "Chemical burn", "Scald"] },
        { q: "Arborescent markings (Lichtenberg figures) seen in?", a: "Lightning", options: ["Electrocution", "Lightning", "Thermal burn", "Chemical burn"] },
        { q: "Joules burn is seen in?", a: "Electrocution (Entry wound)", options: ["Lightning", "Electrocution", "Flame", "Acid"] },
        { q: "Run amok is associated with?", a: "Cannabis", options: ["Opium", "Cannabis", "Cocaine", "Alcohol"] },
        { q: "Magnan's symptom (cocaine bugs) is?", a: "Tactile hallucination", options: ["Visual", "Tactile hallucination", "Auditory", "Olfactory"] },
        { q: "Korsakoff's psychosis is seen in?", a: "Chronic Alcoholism", options: ["Acute Alcoholism", "Chronic Alcoholism", "Opium", "Cannabis"] },
        { q: "Delirium tremens is seen in?", a: "Alcohol withdrawal", options: ["Opium withdrawal", "Alcohol withdrawal", "Cocaine toxicity", "Cannabis"] },
        { q: "Pinpoint pupil is seen in?", a: "Opium / Organophosphorus poisoning", options: ["Datura", "Opium / Organophosphorus poisoning", "Cocaine", "Cannabis"] },
        { q: "Dilated pupil is seen in?", a: "Datura poisoning", options: ["Opium", "Datura poisoning", "Organophosphorus", "Barbiturate"] },
        { q: "Garlic smell of breath is seen in?", a: "Arsenic / Phosphorus / Organophosphorus", options: ["Cyanide", "Arsenic / Phosphorus / Organophosphorus", "Alcohol", "Kerosene"] },
        { q: "Bitter almond smell is seen in?", a: "Cyanide poisoning", options: ["Arsenic", "Cyanide poisoning", "Alcohol", "Opium"] },
        { q: "Burtonian line (Blue line on gums) is seen in?", a: "Lead poisoning", options: ["Mercury", "Lead poisoning", "Arsenic", "Copper"] },
        { q: "Wrist drop is seen in?", a: "Lead poisoning", options: ["Mercury", "Lead poisoning", "Arsenic", "Copper"] },
        { q: "Erethism (Psychic disturbance) is seen in?", a: "Mercury poisoning", options: ["Lead", "Mercury poisoning", "Arsenic", "Iron"] },
        { q: "Rain drop pigmentation is seen in?", a: "Chronic Arsenic poisoning", options: ["Lead", "Chronic Arsenic poisoning", "Mercury", "Copper"] },
        { q: "Aldrich-Mees lines on nails are seen in?", a: "Arsenic poisoning", options: ["Lead", "Arsenic poisoning", "Mercury", "Iron"] },
        { q: "Stomach wash is contraindicated in?", a: "Corrosive poisoning", options: ["Opium", "Corrosive poisoning", "Organophosphorus", "Datura"] },
        { q: "Universal antidote contains?", a: "Charcoal, Magnesium oxide, Tannic acid", options: ["Charcoal only", "Milk", "Charcoal, Magnesium oxide, Tannic acid", "Water"] },
        { q: "Consent age for sexual intercourse (POCSO)?", a: "18 years", options: ["16 years", "18 years", "21 years", "15 years"] },
        { q: "IPC 375 deals with?", a: "Definition of Rape", options: ["Punishment for Rape", "Definition of Rape", "Adultery", "Incest"] },
        { q: "IPC 376 deals with?", a: "Punishment for Rape", options: ["Definition", "Punishment for Rape", "Assault", "Harassment"] },
        { q: "Conduct money is paid to?", a: "Witness in Civil case", options: ["Witness in Criminal case", "Witness in Civil case", "Judge", "Police"] },
        { q: "Hostile witness is declared by?", a: "Judge", options: ["Lawyer", "Judge", "Police", "Jury"] },
        { q: "Professional death sentence?", a: "Erasure of name from register", options: ["Fine", "Jail", "Erasure of name from register", "Suspension"] },
        { q: "Res ipsa loquitur means?", a: "The thing speaks for itself", options: ["Let the master answer", "The thing speaks for itself", "Volunteer not paid", "Good faith"] },
        { q: "Novus actus interveniens means?", a: "New intervening act", options: ["New intervening act", "Contributory negligence", "Shared liability", "None"] },
        { q: "Vicarious liability means?", a: "Employer liable for employee", options: ["Doctor liable for patient", "Employer liable for employee", "Employee liable for self", "None"] },
        { q: "Age of fetus to be viable?", a: "28 weeks (India)", options: ["20 weeks", "24 weeks", "28 weeks", "32 weeks"] },
        { q: "Rule of Haase is for?", a: "Fetal age estimation", options: ["Adult age", "Fetal age estimation", "Sex determination", "Stature"] },
        { q: "Ossification center for lower end of femur appears at?", a: "Birth (9 months)", options: ["8 months", "Birth (9 months)", "1 year", "6 months"] },
        { q: "Ossification center for capitate appears at?", a: "2 months", options: ["Birth", "2 months", "1 year", "3 years"] },
        { q: "First permanent molar erupts at?", a: "6 years", options: ["2 years", "6 years", "12 years", "18 years"] },
        { q: "Third molar (Wisdom tooth) erupts at?", a: "17-25 years", options: ["12-14", "17-25 years", "30-40", "10-12"] },
        { q: "Pre-auricular sulcus is seen in?", a: "Female pelvis", options: ["Male pelvis", "Female pelvis", "Skull", "Femur"] },
        { q: "Obturator foramen shape in males?", a: "Oval / Round", options: ["Triangular", "Oval / Round", "Square", "Irregular"] },
        { q: "Corpus delicti means?", a: "Essence of crime", options: ["Dead body", "Essence of crime", "Criminal", "Weapon"] },
        { q: "Best bone for sex determination?", a: "Pelvis", options: ["Skull", "Pelvis", "Femur", "Mandible"] },
        { q: "Best bone for stature estimation?", a: "Femur", options: ["Humerus", "Femur", "Tibia", "Radius"] },
        { q: "Mummification is seen in?", a: "Dry and hot climate", options: ["Wet and hot", "Dry and hot climate", "Cold and wet", "Freezing"] },
        { q: "Adipocere formation is seen in?", a: "Wet and humid climate", options: ["Dry and hot", "Wet and humid climate", "Freezing", "Deserts"] },
        { q: "Floatation test is for?", a: "Live birth (Lung)", options: ["Dead birth", "Live birth (Lung)", "Drowning", "Poisoning"] },
        { q: "Battered baby syndrome involves?", a: "Multiple fractures of different ages", options: ["Single fracture", "Multiple fractures of different ages", "Burns only", "Bruises only"] },
        { q: "Munchausen syndrome by proxy?", a: "Parent inducing illness in child", options: ["Child faking illness", "Parent inducing illness in child", "Doctor inducing illness", "None"] },
        { q: "Vitriolage is?", a: "Acid throwing", options: ["Poisoning", "Acid throwing", "Burning", "Stabbing"] },
        { q: "Grievous hurt includes fracture of?", a: "Tooth", options: ["Nail", "Tooth", "Hair", "Skin"] },
        { q: "Dying declaration is recorded by?", a: "Magistrate (Preferably)", options: ["Doctor", "Police", "Magistrate (Preferably)", "Any person"] },
        { q: "Subpoena is?", a: "Court order to attend", options: ["Warrant", "Subpoena", "Summons", "Notice"] },
        { q: "Perjury is?", a: "Giving false evidence under oath", options: ["Refusing to answer", "Giving false evidence under oath", "Insulting judge", "None"] },
        { q: "Privileged communication is allowed for?", a: "Notifiable diseases / Venereal diseases", options: ["Gossip", "Notifiable diseases / Venereal diseases", "Personal gain", "Media"] },
        { q: "Consent for autopsy?", a: "Not required in medicolegal cases", options: ["Required from relatives", "Not required in medicolegal cases", "Required from police", "Required from court"] },
        { q: "Exhumation is?", a: "Digging up a buried body", options: ["Burying a body", "Digging up a buried body", "Burning a body", "Preserving a body"] },
        { q: "Embalming is done for?", a: "Preservation of body", options: ["Autopsy", "Preservation of body", "Identification", "Disposal"] },
        { q: "Tache noire is seen in?", a: "Eyes (Sclera) after death", options: ["Skin", "Eyes (Sclera) after death", "Lips", "Nails"] },
        { q: "Kewalal's sign is seen in?", a: "Drowning (Hemorrhage in middle ear)", options: ["Hanging", "Drowning (Hemorrhage in middle ear)", "Strangulation", "Burns"] },
        { q: "Paltauf's hemorrhages are seen in?", a: "Drowning (Lungs)", options: ["Hanging", "Drowning (Lungs)", "Strangulation", "Poisoning"] },
        { q: "Cutis anserina (Goosebumps) is seen in?", a: "Drowning / Rigor Mortis", options: ["Burns", "Drowning / Rigor Mortis", "Hanging", "Poisoning"] }
    ]);
}