if (typeof window.registerSubject === 'function') {
    window.registerSubject('Physiology', [
        { q: "Neuron exposed to toxin blocking voltage-gated K+ channels. Effect on AP?", a: "Prolonged repolarization", options: ["Increased amplitude", "Prolonged repolarization", "Increased conduction velocity", "Decrease threshold"] },
        { q: "Increasing extracellular K+ from 4 to 12 mEq/L. Effect?", a: "Depolarization of RMP with increased excitability", options: ["Hyperpolarization", "Depolarization of RMP with decreased excitability", "Depolarization of RMP with increased excitability", "No change"] },
        { q: "Patient with decreased sensitivity of peripheral chemoreceptors to hypoxia. Effect?", a: "Decreased ventilatory response at high altitude", options: ["Increased ventilation", "Decreased ventilatory response at high altitude", "Hyperventilation", "Decreased response to acidosis"] },
        { q: "In smooth muscle, Ca2+ binds to calmodulin. Next step?", a: "Activation of Myosin Light Chain Kinase (MLCK)", options: ["MLCK activation", "Tropomyosin shift", "Troponin C binding", "Dystrophin activation"] },
        { q: "Frank-Starling law of the heart relates?", a: "Stroke volume to End Diastolic Volume (Preload)", options: ["HR to BP", "Stroke volume to EDV", "Contractility to Afterload", "Conductivity to K+"] },
        { q: "Pace maker of the heart?", a: "SA Node", options: ["AV Node", "Bundle of His", "SA Node", "Purkinje fibers"] },
        { q: "Surfactant is produced by?", a: "Type II Alveolar cells", options: ["Type I cells", "Type II Alveolar cells", "Macrophages", "Goblet cells"] },
        { q: "Main function of surfactant?", a: "Decrease surface tension", options: ["Increase surface tension", "Decrease surface tension", "Increase elasticity", "Prevent edema"] },
        { q: "Hering-Breuer reflex prevents?", a: "Overinflation of lungs", options: ["Collapse of lungs", "Overinflation of lungs", "Coughing", "Sneezing"] },
        { q: "Renin is secreted by?", a: "Juxtaglomerular cells", options: ["Macula densa", "Juxtaglomerular cells", "Podocytes", "Mesangial cells"] },
        { q: "Function of ADH (Vasopressin)?", a: "Water reabsorption in Collecting Duct", options: ["Na+ reabsorption", "Water reabsorption in Collecting Duct", "K+ secretion", "Glucose reabsorption"] },
        { q: "Main site of Glucose reabsorption?", a: "PCT", options: ["PCT", "Loop of Henle", "DCT", "Collecting Duct"] },
        { q: "Hormone responsible for milk ejection?", a: "Oxytocin", options: ["Prolactin", "Oxytocin", "Estrogen", "Progesterone"] },
        { q: "Hormone responsible for milk production?", a: "Prolactin", options: ["Oxytocin", "Prolactin", "FSH", "LH"] },
        { q: "Ovulation is triggered by?", a: "LH Surge", options: ["FSH Surge", "LH Surge", "Progesterone drop", "Estrogen drop"] },
        { q: "Saltatory conduction occurs in?", a: "Myelinated nerve fibers", options: ["Unmyelinated fibers", "Myelinated nerve fibers", "Muscle fibers", "Gap junctions"] },
        { q: "Neurotransmitter at Neuromuscular Junction?", a: "Acetylcholine", options: ["Norepinephrine", "Acetylcholine", "GABA", "Dopamine"] },
        { q: "Bainbridge reflex involves?", a: "Increase in HR due to increased venous return", options: ["Decrease in HR", "Increase in HR due to increased venous return", "Decrease in BP", "Increase in BP"] },
        { q: "Gastrin is secreted by?", a: "G cells of antrum", options: ["Parietal cells", "Chief cells", "G cells of antrum", "D cells"] },
        { q: "Intrinsic Factor is required for absorption of?", a: "Vitamin B12", options: ["Iron", "Calcium", "Vitamin B12", "Folic acid"] },
        { q: "Parietal cells secrete?", a: "HCl and Intrinsic Factor", options: ["Pepsinogen", "HCl and Intrinsic Factor", "Mucus", "Gastrin"] },
        { q: "Chief cells secrete?", a: "Pepsinogen", options: ["HCl", "Pepsinogen", "Gastrin", "Somatostatin"] },
        { q: "Secretin function?", a: "Stimulates bicarbonate rich pancreatic secretion", options: ["Stimulates acid", "Stimulates bicarbonate rich pancreatic secretion", "Contracts gallbladder", "Inhibits insulin"] },
        { q: "CCK function?", a: "Contracts gallbladder and stimulates enzyme rich pancreatic secretion", options: ["Relaxes gallbladder", "Contracts gallbladder and stimulates enzymes", "Stimulates acid", "Inhibits motility"] },
        { q: "Primary respiratory center is located in?", a: "Medulla Oblongata", options: ["Pons", "Medulla Oblongata", "Cerebellum", "Cortex"] },
        { q: "Pneumotaxic center is located in?", a: "Pons", options: ["Medulla", "Pons", "Midbrain", "Spinal cord"] },
        { q: "Central chemoreceptors are sensitive to?", a: "H+ (pH) of CSF / CO2", options: ["O2", "H+ (pH) of CSF / CO2", "Glucose", "Lactic acid"] },
        { q: "Peripheral chemoreceptors are sensitive to?", a: "O2, CO2, and H+", options: ["Only O2", "Only CO2", "O2, CO2, and H+", "Pressure"] },
        { q: "Normal GFR?", a: "125 ml/min", options: ["100 ml/min", "125 ml/min", "80 ml/min", "150 ml/min"] },
        { q: "Substance used to measure GFR?", a: "Inulin", options: ["Creatinine", "Inulin", "PAH", "Urea"] },
        { q: "Substance used to measure Renal Plasma Flow?", a: "PAH", options: ["Inulin", "PAH", "Creatinine", "Glucose"] },
        { q: "Counter current multiplier system is created by?", a: "Loop of Henle", options: ["Vasa recta", "Loop of Henle", "PCT", "Collecting duct"] },
        { q: "Resting Membrane Potential of nerve?", a: "-70 mV", options: ["-90 mV", "-70 mV", "-55 mV", "+30 mV"] },
        { q: "Ion responsible for Depolarization?", a: "Sodium influx", options: ["Potassium efflux", "Sodium influx", "Calcium influx", "Chloride influx"] },
        { q: "Ion responsible for Repolarization?", a: "Potassium efflux", options: ["Sodium influx", "Potassium efflux", "Calcium influx", "Chloride efflux"] },
        { q: "Absolute refractory period corresponds to?", a: "Depolarization and early repolarization", options: ["Hyperpolarization", "Depolarization and early repolarization", "Resting state", "Late repolarization"] },
        { q: "Cortisol is secreted by?", a: "Zona Fasciculata", options: ["Zona Glomerulosa", "Zona Fasciculata", "Zona Reticularis", "Medulla"] },
        { q: "Aldosterone is secreted by?", a: "Zona Glomerulosa", options: ["Zona Glomerulosa", "Zona Fasciculata", "Zona Reticularis", "Medulla"] },
        { q: "Androgens are secreted by?", a: "Zona Reticularis", options: ["Glomerulosa", "Fasciculata", "Reticularis", "Medulla"] },
        { q: "Catecholamines are secreted by?", a: "Adrenal Medulla", options: ["Cortex", "Adrenal Medulla", "Pituitary", "Thyroid"] },
        { q: "Calcitonin is secreted by?", a: "Parafollicular C cells of Thyroid", options: ["Parathyroid", "Parafollicular C cells of Thyroid", "Follicular cells", "Pancreas"] },
        { q: "Parathyroid hormone function?", a: "Increases serum Calcium", options: ["Decreases serum Calcium", "Increases serum Calcium", "Increases Phosphate", "Decreases Magnesium"] },
        { q: "Sertoli cells secrete?", a: "Inhibin and Anti-Mullerian Hormone", options: ["Testosterone", "Inhibin and Anti-Mullerian Hormone", "LH", "FSH"] },
        { q: "Leydig cells secrete?", a: "Testosterone", options: ["Inhibin", "Testosterone", "Estrogen", "FSH"] },
        { q: "Corpus Luteum secretes?", a: "Progesterone", options: ["Estrogen only", "Progesterone", "FSH", "LH"] },
        { q: "Insulin is secreted by?", a: "Beta cells of Pancreas", options: ["Alpha cells", "Beta cells", "Delta cells", "F cells"] },
        { q: "Glucagon is secreted by?", a: "Alpha cells of Pancreas", options: ["Alpha cells", "Beta cells", "Delta cells", "Acini"] },
        { q: "Afferent signal of Bainbridge reflex travels via?", a: "Vagus nerve", options: ["Sympathetic", "Vagus nerve", "Glossopharyngeal", "Spinal nerves"] }
    ]);
}