if (typeof window.registerSubject === 'function') {
    window.registerSubject('Pathology', [
        { q: "Which of the following is not a feature of irreversible cell injury?", a: "Fatty change in liver", options: ["Loss of mitochondrial function", "Severe membrane damage", "Fatty change in liver", "Nuclear karyolysis"] },
        { q: "In hypoxic injury, the first biochemical event leading to cell swelling is:", a: "Decrease in ATP", options: ["Ribosomal detachment from RER", "Decrease in ATP", "Increased lactic acid formation", "Mitochondrial calcification"] },
        { q: "42M, cough, night sweats, weight loss. CXR cavitary lesion. Biopsy: granulomas with central cheesy necrosis. Type?", a: "Caseous", options: ["Liquefactive", "Caseous", "Fat", "Fibrinoid"] },
        { q: "60M, severe chest pain 18h. Myocardial biopsy: eosinophilic fibers, loss of nuclei. Process?", a: "Irreversible ischemic injury producing coagulative necrosis", options: ["Reversible injury", "Programmed cell death", "Irreversible ischemic injury producing coagulative necrosis", "Enzymatic destruction"] },
        { q: "Psammoma bodies are seen in?", a: "Papillary Carcinoma of Thyroid", options: ["Follicular CA", "Papillary Carcinoma of Thyroid", "Medullary CA", "Anaplastic CA"] },
        { q: "Reed-Sternberg cells are characteristic of?", a: "Hodgkin's Lymphoma", options: ["Non-Hodgkin's Lymphoma", "Hodgkin's Lymphoma", "Burkitt's Lymphoma", "Multiple Myeloma"] },
        { q: "Starry sky appearance is seen in?", a: "Burkitt's Lymphoma", options: ["Hodgkin's Lymphoma", "Burkitt's Lymphoma", "CLL", "ALL"] },
        { q: "Philadelphia chromosome (t9;22) is seen in?", a: "CML", options: ["AML", "CLL", "CML", "ALL"] },
        { q: "Auer rods are seen in?", a: "AML", options: ["AML", "CML", "ALL", "CLL"] },
        { q: "Orphan Annie eye nuclei are seen in?", a: "Papillary Carcinoma Thyroid", options: ["Follicular CA", "Papillary Carcinoma Thyroid", "Medullary CA", "Hurthle cell adenoma"] },
        { q: "Call-Exner bodies are seen in?", a: "Granulosa Cell Tumor", options: ["Dysgerminoma", "Granulosa Cell Tumor", "Yolk Sac Tumor", "Teratoma"] },
        { q: "Schiller-Duval bodies are seen in?", a: "Yolk Sac Tumor", options: ["Seminoma", "Yolk Sac Tumor", "Choriocarcinoma", "Embryonal CA"] },
        { q: "Kimmelstiel-Wilson nodules are seen in?", a: "Diabetic Nephropathy", options: ["Amyloidosis", "Diabetic Nephropathy", "SLE", "Goodpasture's"] },
        { q: "Crescentic Glomerulonephritis is characterized by?", a: "Rapidly Progressive Glomerulonephritis (RPGN)", options: ["Nephrotic Syndrome", "RPGN", "Chronic Glomerulonephritis", "Minimal Change Disease"] },
        { q: "Most common lung cancer in non-smokers?", a: "Adenocarcinoma", options: ["Squamous cell CA", "Adenocarcinoma", "Small cell CA", "Large cell CA"] },
        { q: "Marker for Hepatocellular Carcinoma?", a: "AFP", options: ["CEA", "CA 19-9", "AFP", "PSA"] },
        { q: "Marker for Pancreatic Cancer?", a: "CA 19-9", options: ["CEA", "CA 19-9", "AFP", "CA 125"] },
        { q: "Marker for Ovarian Cancer?", a: "CA 125", options: ["CEA", "CA 19-9", "AFP", "CA 125"] },
        { q: "Heart failure cells are?", a: "Hemosiderin laden macrophages", options: ["Lymphocytes", "Hemosiderin laden macrophages", "Neutrophils", "Fibroblasts"] },
        { q: "Nutmeg liver is seen in?", a: "Chronic Venous Congestion (Right Heart Failure)", options: ["Cirrhosis", "Chronic Venous Congestion", "Fatty Liver", "Hepatitis"] },
        { q: "Birbeck granules are seen in?", a: "Langerhans Cell Histiocytosis", options: ["Sarcoidosis", "Langerhans Cell Histiocytosis", "Tuberculosis", "Leprosy"] },
        { q: "Councilman bodies are seen in?", a: "Viral Hepatitis (Apoptotic bodies)", options: ["Alcoholic Hepatitis", "Viral Hepatitis", "Fatty Liver", "Cirrhosis"] },
        { q: "Mallory Hyaline is seen in?", a: "Alcoholic Liver Disease", options: ["Viral Hepatitis", "Alcoholic Liver Disease", "Wilson's Disease", "Hemochromatosis"] },
        { q: "Antinuclear Antibody (ANA) is most sensitive for?", a: "SLE", options: ["Rheumatoid Arthritis", "SLE", "Scleroderma", "Sjogren's Syndrome"] },
        { q: "Anti-dsDNA is specific for?", a: "SLE", options: ["Drug induced Lupus", "SLE", "Scleroderma", "MCTD"] },
        { q: "Anti-Centromere antibody is seen in?", a: "CREST Syndrome", options: ["Diffuse Scleroderma", "CREST Syndrome", "SLE", "Polymyositis"] },
        { q: "Anti-Scl70 antibody is seen in?", a: "Diffuse Systemic Sclerosis", options: ["CREST", "Diffuse Systemic Sclerosis", "SLE", "RA"] },
        { q: "C-ANCA is associated with?", a: "Wegener's Granulomatosis", options: ["Churg-Strauss", "Wegener's Granulomatosis", "Microscopic Polyangiitis", "PAN"] },
        { q: "P-ANCA is associated with?", a: "Microscopic Polyangiitis / Churg-Strauss", options: ["Wegener's", "Microscopic Polyangiitis / Churg-Strauss", "Kawasaki", "Takayasu"] },
        { q: "Aschoff bodies are characteristic of?", a: "Rheumatic Heart Disease", options: ["MI", "Rheumatic Heart Disease", "Endocarditis", "Myocarditis"] },
        { q: "Anitschkow cells are seen in?", a: "Rheumatic Heart Disease", options: ["TB", "Rheumatic Heart Disease", "Sarcoidosis", "Syphilis"] },
        { q: "Most common cause of Nephrotic Syndrome in children?", a: "Minimal Change Disease", options: ["Membranous", "Minimal Change Disease", "FSGS", "IgA Nephropathy"] },
        { q: "Tram-track appearance of GBM is seen in?", a: "MPGN", options: ["Membranous", "MPGN", "FSGS", "Minimal Change"] },
        { q: "Spike and Dome appearance of GBM is seen in?", a: "Membranous Glomerulonephritis", options: ["MPGN", "Membranous Glomerulonephritis", "IgA Nephropathy", "Goodpasture"] },
        { q: "Most common thyroid cancer?", a: "Papillary Carcinoma", options: ["Follicular", "Papillary", "Medullary", "Anaplastic"] },
        { q: "Amyloid associated with Medullary Thyroid Carcinoma?", a: "Procalcitonin (A Cal)", options: ["AL", "AA", "A Cal", "AB2M"] },
        { q: "Signet ring cells are seen in?", a: "Diffuse Gastric Carcinoma", options: ["Intestinal Gastric CA", "Diffuse Gastric Carcinoma", "Colon CA", "Esophageal CA"] },
        { q: "Linitis Plastica is seen in?", a: "Diffuse Gastric Cancer", options: ["Peptic Ulcer", "Diffuse Gastric Cancer", "Lymphoma", "GIST"] },
        { q: "Most common tumor of appendix?", a: "Carcinoid", options: ["Adenocarcinoma", "Carcinoid", "Lymphoma", "Mucocele"] },
        { q: "Codman's Triangle is seen in?", a: "Osteosarcoma", options: ["Ewing's Sarcoma", "Osteosarcoma", "Chondrosarcoma", "Giant Cell Tumor"] }
    ]);
}