if (typeof window.registerSubject === 'function') {
    window.registerSubject('Microbiology', [
        { q: "Medical Superintendent found items to be disposed. Identify correct colour codes: (Anatomical waste, Sharps, Plastics, Glass)?", a: "Yellow, White, Red, Blue", options: ["Yellow, White, Red, Blue", "Red, Yellow, Blue, White", "Yellow, Red, White, Blue", "Black, Red, Blue, Yellow"] }, 
        { q: "Doctor couple went to Mars. Bf exposed to rat flea, gf to ardeid bird. Admitted in?", a: "Bf Isolation and gf general ward", options: ["Both in ICU", "Bf Isolation and gf general ward", "Both isolation ward", "Gf Isolation and bf general ward"] },
        { q: "Youtuber bitten by Krait. All are responsibilities of doctor EXCEPT?", a: "Written informed consent before giving antivenom", options: ["Raise MLC", "Inform police", "Notify Government of India", "Written informed consent before giving antivenom"] },
        { q: "54 yr with b/l lower limb flaccid paralysis + arreflexia. CSF shows albumino-cytologic dissociation. Diagnosis and Rx?", a: "Guillain Barre syndrome, IVIg", options: ["Polio, no Rx", "Cauda equina syndrome, no Rx", "Guillain Barre syndrome, IVIg", "Cord transection syndrome, no Rx"] },
        { q: "3 months old child with centripetally distributed centrifugally spreading rash. Diagnosis?", a: "Chickenpox (Varicella)", options: ["Measles", "Smallpox", "Chickenpox", "Herpes Zoster"] },
        { q: "Drug of choice for Scrub Typhus?", a: "Doxycycline", options: ["Penicillin", "Doxycycline", "Ceftriaxone", "Metronidazole"] },
        { q: "Vector for Japanese Encephalitis?", a: "Culex tritaeniorhynchus", options: ["Anopheles", "Aedes", "Culex tritaeniorhynchus", "Mansonia"] },
        { q: "Most common cause of UTI?", a: "E. coli", options: ["Klebsiella", "Proteus", "E. coli", "Pseudomonas"] },
        { q: "Widal test is used for?", a: "Typhoid Fever", options: ["Malaria", "Typhoid Fever", "Dengue", "Typhus"] },
        { q: "VDRL is a screening test for?", a: "Syphilis", options: ["Gonorrhea", "Syphilis", "Chancroid", "HIV"] },
        { q: "Rice water stool is characteristic of?", a: "Vibrio cholerae", options: ["E. coli", "Shigella", "Vibrio cholerae", "Salmonella"] },
        { q: "Gas gangrene is caused by?", a: "Clostridium perfringens", options: ["Clostridium tetani", "Clostridium botulinum", "Clostridium perfringens", "Bacillus anthracis"] },
        { q: "Negri bodies are seen in?", a: "Rabies", options: ["Polio", "Rabies", "Herpes", "Measles"] },
        { q: "Satellitism is shown by?", a: "Haemophilus influenzae", options: ["Staphylococcus aureus", "Haemophilus influenzae", "Streptococcus pneumoniae", "Klebsiella"] },
        { q: "Elek's gel precipitation test is for?", a: "Corynebacterium diphtheriae", options: ["Clostridium tetani", "Corynebacterium diphtheriae", "Bacillus anthracis", "E. coli"] },
        { q: "Malignant Pustule is seen in?", a: "Anthrax", options: ["Plague", "Anthrax", "Tularemia", "Brucellosis"] },
        { q: "Hidradenitis suppurativa is associated with?", a: "Staphylococcus aureus", options: ["Streptococcus", "Staphylococcus aureus", "Pseudomonas", "E. coli"] },
        { q: "Rheumatic fever is a sequela of infection with?", a: "Group A Streptococcus", options: ["Group B Streptococcus", "Group A Streptococcus", "Staph aureus", "Enterococcus"] },
        { q: "HBsAg positive indicates?", a: "Active Hepatitis B infection", options: ["Past infection", "Active Hepatitis B infection", "Immunity", "Vaccination"] },
        { q: "Vector for Dengue?", a: "Aedes aegypti", options: ["Anopheles", "Culex", "Aedes aegypti", "Sandfly"] },
        { q: "Most common cause of traveler's diarrhea?", a: "ETEC", options: ["EPEC", "ETEC", "EIEC", "EHEC"] },
        { q: "Bacteria causing hemolytic uremic syndrome?", a: "E. coli O157:H7", options: ["Shigella", "Salmonella", "E. coli O157:H7", "Campylobacter"] },
        { q: "Campylobacter jejuni is associated with?", a: "Guillain-Barre Syndrome", options: ["HUS", "Guillain-Barre Syndrome", "Reactive Arthritis", "Meningitis"] },
        { q: "Standard test for HIV confirmation?", a: "Western Blot / Immunoblot", options: ["ELISA", "Western Blot / Immunoblot", "PCR", "Rapid Test"] },
        { q: "Drug of choice for Methicillin Resistant Staph Aureus (MRSA)?", a: "Vancomycin", options: ["Methicillin", "Vancomycin", "Linezolid", "Ceftriaxone"] },
        { q: "Example of a live attenuated vaccine?", a: "BCG", options: ["DPT", "BCG", "Hepatitis B", "Rabies"] },
        { q: "Causative agent of Whooping Cough?", a: "Bordetella pertussis", options: ["Haemophilus influenzae", "Bordetella pertussis", "Mycoplasma pneumoniae", "Legionella"] },
        { q: "Type of hypersensitivity in Tuberculin test?", a: "Type IV", options: ["Type I", "Type II", "Type III", "Type IV"] },
        { q: "Bacteria known as 'Blue Pus Bacillus'?", a: "Pseudomonas aeruginosa", options: ["Proteus", "Pseudomonas aeruginosa", "Klebsiella", "E. coli"] },
        { q: "Swarming motility is characteristic of?", a: "Proteus mirabilis", options: ["E. coli", "Proteus mirabilis", "Pseudomonas", "Salmonella"] },
        { q: "Metachromatic granules are seen in?", a: "Corynebacterium diphtheriae", options: ["Clostridium", "Corynebacterium diphtheriae", "Bacillus", "Mycobacterium"] },
        { q: "Lepromin test is positive in?", a: "Tuberculoid Leprosy", options: ["Lepromatous Leprosy", "Tuberculoid Leprosy", "Indeterminate Leprosy", "LL"] },
        { q: "Acid fast staining is used for?", a: "Mycobacterium", options: ["Staphylococcus", "Mycobacterium", "Streptococcus", "E. coli"] },
        { q: "Culture medium for Mycobacterium tuberculosis?", a: "LJ Medium", options: ["MacConkey", "LJ Medium", "Blood Agar", "Chocolate Agar"] },
        { q: "Significant bacteriuria count?", a: "> 10^5 CFU/ml", options: ["> 10^3 CFU/ml", "> 10^5 CFU/ml", "> 10^2 CFU/ml", "> 10^4 CFU/ml"] },
        { q: "Most common cause of nosocomial infection?", a: "E. coli / Staph aureus", options: ["Pseudomonas", "E. coli / Staph aureus", "Klebsiella", "Candida"] },
        { q: "Sterilization of heat sensitive instruments?", a: "Ethylene Oxide / Plasma", options: ["Autoclave", "Hot Air Oven", "Ethylene Oxide / Plasma", "Boiling"] },
        { q: "Temperature and time for Autoclave?", a: "121°C for 15 mins", options: ["100°C for 30 mins", "121°C for 15 mins", "160°C for 1 hour", "134°C for 3 mins"] },
        { q: "Indicator for Autoclave efficiency?", a: "Geobacillus stearothermophilus", options: ["Bacillus subtilis", "Geobacillus stearothermophilus", "Clostridium tetani", "E. coli"] },
        { q: "Hot Air Oven is used for?", a: "Glassware, Powders, Oils", options: ["Culture media", "Glassware, Powders, Oils", "Plastics", "Rubber"] },
        { q: "Disinfectant for blood spill?", a: "Sodium Hypochlorite", options: ["Alcohol", "Sodium Hypochlorite", "Phenol", "Glutaraldehyde"] },
        { q: "Antigen used in Widal test?", a: "O and H antigens", options: ["Vi antigen", "O and H antigens", "K antigen", "Capsular antigen"] },
        { q: "Weil-Felix test is used for?", a: "Rickettsial infections", options: ["Viral infections", "Rickettsial infections", "Fungal infections", "Parasitic infections"] },
        { q: "Q fever is caused by?", a: "Coxiella burnetii", options: ["Rickettsia rickettsii", "Coxiella burnetii", "Rickettsia prowazekii", "Orientia tsutsugamushi"] },
        { q: "Vector for Kala-azar?", a: "Sandfly (Phlebotomus)", options: ["Tsetse fly", "Sandfly (Phlebotomus)", "Anopheles", "Aedes"] },
        { q: "LD bodies are seen in?", a: "Kala-azar (Leishmaniasis)", options: ["Malaria", "Kala-azar (Leishmaniasis)", "Trypanosomiasis", "Filariasis"] },
        { q: "Drug of choice for Kala-azar in India?", a: "Liposomal Amphotericin B", options: ["Sodium Stibogluconate", "Liposomal Amphotericin B", "Miltefosine", "Pentamidine"] },
        { q: "Cysticercus cellulosae is larval stage of?", a: "Taenia solium", options: ["Taenia saginata", "Taenia solium", "Echinococcus", "Hymenolepis"] },
        { q: "Hydatid cyst is caused by?", a: "Echinococcus granulosus", options: ["Taenia solium", "Echinococcus granulosus", "Diphyllobothrium", "Fasciola"] },
        { q: "Definitive host for Toxoplasma gondii?", a: "Cat", options: ["Dog", "Cat", "Man", "Pig"] },
        { q: "Malaria with cerebral complications is caused by?", a: "Plasmodium falciparum", options: ["P. vivax", "P. falciparum", "P. ovale", "P. malariae"] },
        { q: "Most common opportunistic infection in HIV in India?", a: "Tuberculosis", options: ["Candidiasis", "Tuberculosis", "Cryptococcosis", "Pneumocystis"] },
        { q: "Oral thrush is caused by?", a: "Candida albicans", options: ["Aspergillus", "Candida albicans", "Cryptococcus", "Histoplasma"] },
        { q: "Cryptococcal meningitis is diagnosed by?", a: "India Ink preparation", options: ["Gram stain", "India Ink preparation", "Giemsa stain", "Acid fast stain"] },
        { q: "Fungus ball in lung cavity?", a: "Aspergilloma", options: ["Candidoma", "Aspergilloma", "Histoplasmoma", "Cryptococcoma"] },
        { q: "Dimorphic fungi include?", a: "Histoplasma, Blastomyces, Coccidioides", options: ["Candida, Aspergillus", "Histoplasma, Blastomyces, Coccidioides", "Cryptococcus, Rhizopus", "Mucor, Penicillium"] },
        { q: "Rhino-cerebral mucormycosis is common in?", a: "Diabetics (DKA)", options: ["HIV", "Diabetics (DKA)", "Transplant patients", "Neonates"] },
        { q: "Tinea corporis is?", a: "Ringworm of body", options: ["Scalp", "Body", "Groin", "Feet"] },
        { q: "Viral marker for high infectivity in Hepatitis B?", a: "HBeAg", options: ["HBsAg", "HBeAg", "Anti-HBc", "Anti-HBs"] },
        { q: "Window period in Hepatitis B is characterized by?", a: "Anti-HBc IgM only", options: ["HBsAg", "Anti-HBc IgM only", "Anti-HBs", "HBeAg"] },
        { q: "Hepatitis C is most commonly transmitted by?", a: "Blood transfusion / IV drug use", options: ["Fecal-oral", "Blood transfusion / IV drug use", "Sexual", "Vertical"] },
        { q: "Hepatitis E transmission?", a: "Fecal-oral", options: ["Blood", "Sexual", "Fecal-oral", "Vector"] },
        { q: "Negri bodies are pathognomonic of?", a: "Rabies", options: ["Polio", "Rabies", "HSV", "CMV"] },
        { q: "Owl's eye inclusion bodies are seen in?", a: "CMV", options: ["HSV", "CMV", "Rabies", "Smallpox"] },
        { q: "Cowdry type A inclusion bodies are seen in?", a: "Herpes Simplex / Varicella", options: ["CMV", "Herpes Simplex / Varicella", "Rabies", "Poxvirus"] },
        { q: "Tzank smear is used for?", a: "Herpes / Varicella / Pemphigus", options: ["Leprosy", "Herpes / Varicella / Pemphigus", "Syphilis", "Tinea"] },
        { q: "Paul-Bunnell test is for?", a: "Infectious Mononucleosis (EBV)", options: ["CMV", "Infectious Mononucleosis (EBV)", "HIV", "Herpes"] },
        { q: "Breakbone fever is?", a: "Dengue", options: ["Chikungunya", "Dengue", "Malaria", "Typhoid"] },
        { q: "Vector for Chikungunya?", a: "Aedes aegypti", options: ["Culex", "Aedes aegypti", "Anopheles", "Tick"] },
        { q: "Kyasanur Forest Disease vector?", a: "Tick (Haemaphysalis)", options: ["Mosquito", "Tick (Haemaphysalis)", "Mite", "Flea"] },
        { q: "Crimean-Congo Hemorrhagic Fever vector?", a: "Hyalomma Tick", options: ["Aedes", "Hyalomma Tick", "Sandfly", "Louse"] },
        { q: "Lyme disease vector?", a: "Ixodes Tick", options: ["Dermacentor", "Ixodes Tick", "Pediculus", "Xenopsylla"] },
        { q: "Plague vector?", a: "Rat Flea (Xenopsylla cheopis)", options: ["Louse", "Rat Flea (Xenopsylla cheopis)", "Tick", "Mite"] },
        { q: "Epidemic Typhus vector?", a: "Louse (Pediculus humanus)", options: ["Flea", "Louse (Pediculus humanus)", "Tick", "Mite"] },
        { q: "Endemic Typhus vector?", a: "Rat Flea", options: ["Louse", "Rat Flea", "Tick", "Mite"] },
        { q: "Scrub Typhus vector?", a: "Trombiculid Mite (Chigger)", options: ["Tick", "Trombiculid Mite (Chigger)", "Louse", "Flea"] },
        { q: "Eschar is seen in?", a: "Scrub Typhus / Anthrax", options: ["Malaria", "Scrub Typhus / Anthrax", "Dengue", "Typhoid"] },
        { q: "Weil's disease is severe form of?", a: "Leptospirosis", options: ["Brucellosis", "Leptospirosis", "Lyme disease", "Syphilis"] },
        { q: "Leptospirosis transmission?", a: "Contact with rat urine / water", options: ["Bite", "Contact with rat urine / water", "Inhalation", "Fecal-oral"] },
        { q: "Brucellosis typically presents as?", a: "Undulant fever", options: ["Rash", "Undulant fever", "Jaundice", "Diarrhea"] },
        { q: "Malta fever is?", a: "Brucellosis", options: ["Typhoid", "Brucellosis", "Q fever", "Leptospirosis"] },
        { q: "Sabin-Feldman dye test is for?", a: "Toxoplasmosis", options: ["Leishmaniasis", "Toxoplasmosis", "Trypanosomiasis", "Malaria"] },
        { q: "Casoni's test is for?", a: "Hydatid cyst", options: ["Ascariasis", "Hydatid cyst", "Filariasis", "Schistosomiasis"] },
        { q: "Montenegro test is for?", a: "Leishmaniasis", options: ["Leprosy", "Leishmaniasis", "TB", "Sarcoidosis"] },
        { q: "Most common cause of meningitis in neonates?", a: "GBS / E. coli / Listeria", options: ["Meningococcus", "GBS / E. coli / Listeria", "Pneumococcus", "H. influenzae"] },
        { q: "Most common cause of meningitis in adults?", a: "Streptococcus pneumoniae", options: ["N. meningitidis", "Streptococcus pneumoniae", "H. influenzae", "Listeria"] },
        { q: "Waterhouse-Friderichsen syndrome is associated with?", a: "Meningococcemia", options: ["Pneumococcemia", "Meningococcemia", "Staph sepsis", "Gonococcemia"] },
        { q: "Mycoplasma pneumoniae causes?", a: "Atypical Pneumonia (Walking pneumonia)", options: ["Lobar pneumonia", "Atypical Pneumonia", "Abscess", "Empyema"] },
        { q: "Fried egg colonies are seen in?", a: "Mycoplasma", options: ["Mycobacterium", "Mycoplasma", "Nocardia", "Actinomyces"] },
        { q: "Sulfur granules in pus are seen in?", a: "Actinomycosis", options: ["Nocardiosis", "Actinomycosis", "Tuberculosis", "Botryomycosis"] },
        { q: "Acid fast branching filaments?", a: "Nocardia", options: ["Actinomyces", "Nocardia", "Streptomyces", "Corynebacterium"] },
        { q: "Non-acid fast branching filaments?", a: "Actinomyces", options: ["Nocardia", "Actinomyces", "Mycobacterium", "Rhodococcus"] },
        { q: "Nagler's reaction is for?", a: "Clostridium perfringens", options: ["Clostridium tetani", "Clostridium perfringens", "Bacillus anthracis", "Staph aureus"] },
        { q: "Reverse CAMP test is positive in?", a: "Clostridium perfringens", options: ["GBS", "Clostridium perfringens", "Listeria", "Staph aureus"] },
        { q: "String test is for?", a: "Vibrio cholerae", options: ["E. coli", "Vibrio cholerae", "Salmonella", "Shigella"] },
        { q: "Darting motility is seen in?", a: "Vibrio cholerae", options: ["Campylobacter", "Vibrio cholerae", "Pseudomonas", "Proteus"] }
    ]);
}