if (typeof window.registerSubject === 'function') {
    window.registerSubject('Pediatrics', [
        { q: "3y boy, familial short stature suspect. Mother 146cm, Father 150cm. Predicted height?", a: "154.5 cm", options: ["154.5 cm", "159.5 cm", "148 cm", "165 cm"] },
        { q: "Child stands with support, pincer grasp present, cannot walk. Other milestone likely present?", a: "Sit without support", options: ["Sit without support", "Copy a line", "Complete bowel control", "Identify colors"] }, 
        { q: "Infant of Diabetic Mother (IDM). LEAST likely finding?", a: "SGA", options: ["Caudal regression syndrome", "Myelomeningocele", "SGA", "VSD"] },
        { q: "Kangaroo mother care is advised for?", a: "LBW baby", options: ["AGA baby", "LGA baby", "Posterm baby", "LBW baby"] },
        { q: "Most children stand without support by?", a: "1 year (10-12 months)", options: ["6 months", "1 year", "2 years", "18 months"] },
        { q: "Delayed dentition is defined as no teeth by?", a: "13 months", options: ["10 months", "13 months", "15 months", "18 months"] },
        { q: "Vitamin A prophylaxis dose at 9 months?", a: "1 lakh IU", options: ["1 lakh IU", "2 lakh IU", "50k IU", "5 lakh IU"] },
        { q: "Measles vaccine is given at?", a: "9 months", options: ["Birth", "6 weeks", "9 months", "15 months"] },
        { q: "Most common cause of diarrhea in children?", a: "Rotavirus", options: ["E. coli", "Rotavirus", "Adenovirus", "Salmonella"] },
        { q: "Drug of choice for Neonatal Jaundice?", a: "Phototherapy", options: ["Phenobarbitone", "Phototherapy", "Exchange Transfusion", "IVIG"] },
        { q: "Kramer's rule is used for?", a: "Clinical assessment of Jaundice", options: ["Burn area", "Clinical assessment of Jaundice", "Dehydration", "Malnutrition"] },
        { q: "Tetralogy of Fallot components include all EXCEPT?", a: "ASD", options: ["VSD", "Pulmonary Stenosis", "Overriding Aorta", "ASD"] },
        { q: "Boot shaped heart is seen in?", a: "Tetralogy of Fallot", options: ["TGA", "TOF", "TAPVC", "Truncus Arteriosus"] },
        { q: "Egg on side appearance of heart?", a: "Transposition of Great Arteries (TGA)", options: ["TOF", "TGA", "TAPVC", "Ebstein's"] },
        { q: "Snowman appearance (Figure of 8) of heart?", a: "TAPVC (Supracardiac)", options: ["TOF", "TGA", "TAPVC", "VSD"] },
        { q: "Treatment of choice for Kawasaki disease?", a: "IVIG + Aspirin", options: ["Steroids", "IVIG + Aspirin", "Antibiotics", "Methotrexate"] },
        { q: "Koplik's spots are seen in?", a: "Measles", options: ["Rubella", "Measles", "Mumps", "Chickenpox"] },
        { q: "Dew drop on rose petal rash is seen in?", a: "Chickenpox", options: ["Measles", "Smallpox", "Chickenpox", "Herpes Zoster"] },
        { q: "Croup is caused by?", a: "Parainfluenza virus", options: ["Influenza", "Parainfluenza virus", "RSV", "Adenovirus"] },
        { q: "Steeple sign on X-ray neck?", a: "Croup", options: ["Epiglottitis", "Croup", "Foreign body", "Abscess"] },
        { q: "Thumb sign on X-ray neck?", a: "Epiglottitis", options: ["Croup", "Epiglottitis", "Retropharyngeal abscess", "Foreign body"] },
        { q: "Hot potato voice is seen in?", a: "Retropharyngeal / Peritonsillar abscess", options: ["Croup", "Epiglottitis", "Retropharyngeal / Peritonsillar abscess", "Laryngomalacia"] },
        { q: "Most common cause of stridor in newborn?", a: "Laryngomalacia", options: ["Vocal cord palsy", "Laryngomalacia", "Subglottic stenosis", "Hemangioma"] },
        { q: "Omega shaped epiglottis is seen in?", a: "Laryngomalacia", options: ["Epiglottitis", "Croup", "Laryngomalacia", "Tracheomalacia"] },
        { q: "Most common cause of short stature?", a: "Constitutional delay", options: ["Hypothyroidism", "GH deficiency", "Constitutional delay", "Familial"] },
        { q: "Physiological jaundice appears on?", a: "2nd-3rd day", options: ["1st day", "2nd-3rd day", "1st week", "2nd week"] },
        { q: "Pathological jaundice appears on?", a: "1st day (<24 hours)", options: ["1st day", "3rd day", "5th day", "7th day"] },
        { q: "Breast milk jaundice usually appears?", a: "After 1st week (Late)", options: ["1st day", "3rd day", "After 1st week", "At birth"] },
        { q: "Most common congenital heart disease?", a: "VSD", options: ["ASD", "VSD", "PDA", "TOF"] },
        { q: "Machinery murmur is seen in?", a: "PDA", options: ["VSD", "ASD", "PDA", "TOF"] },
        { q: "Cyanosis at birth is seen in?", a: "TGA", options: ["TOF", "TGA", "VSD", "PDA"] },
        { q: "Most common cyanotic heart disease?", a: "TOF", options: ["TGA", "TOF", "TAPVC", "Truncus"] },
        { q: "Cyanotic spell (Tet spell) is seen in?", a: "TOF", options: ["TGA", "TOF", "VSD", "ASD"] },
        { q: "Treatment of Tet spell?", a: "Knee-chest position / Oxygen / Morphine", options: ["Digoxin", "Diuretics", "Knee-chest position / Oxygen / Morphine", "Atropine"] },
        { q: "Surfactant deficiency causes?", a: "HMD / RDS", options: ["TTN", "HMD / RDS", "MAS", "Pneumonia"] },
        { q: "Ground glass appearance on CXR in neonate?", a: "HMD / RDS", options: ["TTN", "MAS", "HMD / RDS", "CDH"] },
        { q: "Wilson's disease is defect in?", a: "Copper metabolism", options: ["Iron", "Copper", "Zinc", "Magnesium"] },
        { q: "Kayser-Fleischer ring is seen in?", a: "Wilson's disease", options: ["Menke's disease", "Wilson's disease", "Hemochromatosis", "Cataract"] },
        { q: "Down syndrome trisomy?", a: "Trisomy 21", options: ["18", "13", "21", "22"] },
        { q: "Edward syndrome trisomy?", a: "Trisomy 18", options: ["21", "18", "13", "15"] },
        { q: "Patau syndrome trisomy?", a: "Trisomy 13", options: ["21", "18", "13", "16"] },
        { q: "Turner syndrome karyotype?", a: "45, XO", options: ["46, XX", "45, XO", "47, XXY", "47, XXX"] },
        { q: "Klinefelter syndrome karyotype?", a: "47, XXY", options: ["46, XY", "45, XO", "47, XXY", "47, XYY"] },
        { q: "Cystic Fibrosis inheritance?", a: "Autosomal Recessive", options: ["AD", "AR", "XR", "XD"] },
        { q: "Sweat chloride test is for?", a: "Cystic Fibrosis", options: ["G6PD", "Cystic Fibrosis", "Galactosemia", "PKU"] },
        { q: "Most common malignancy in children?", a: "ALL (Leukemia)", options: ["Brain tumor", "ALL", "Lymphoma", "Wilms tumor"] },
        { q: "Wilms tumor arises from?", a: "Kidney", options: ["Adrenal", "Kidney", "Liver", "Bone"] },
        { q: "Neuroblastoma arises from?", a: "Adrenal medulla / Sympathetic chain", options: ["Kidney", "Adrenal medulla", "Brain", "Liver"] },
        { q: "Rickets is due to deficiency of?", a: "Vitamin D", options: ["Vitamin A", "Vitamin C", "Vitamin D", "Calcium"] },
        { q: "Scurvy is due to deficiency of?", a: "Vitamin C", options: ["Vitamin D", "Vitamin C", "Vitamin B12", "Vitamin K"] }
    ]);
}