// FMGE Ultimate Revision - Surgery Module
// Source: MIST SURGERY SUBJECT WISE TEST (5th Dec 2025)

if (typeof window.registerSubject === 'function') {
    window.registerSubject('Surgery', [
        { q: "6y child, midline neck swelling below hyoid, moves with swallowing and tongue protrusion. USG normal thyroid. Mgmt?", a: "Sistrunk operation", options: ["Simple cyst excision", "Sistrunk operation", "Observation", "Incision and drainage"] },
        { q: "2y child, large soft compressible swelling in posterior triangle/axilla, transilluminant. Treatment?", a: "Surgical excision + adjunct sclerotherapy", options: ["High-dose steroids", "Radiotherapy", "Surgical excision + adjunct sclerotherapy", "Needle aspiration"] },
        { q: "Neonate, choking/cyanosis on feed. Catheter stops 10cm. X-ray: tube coiled, air in stomach. Type?", a: "Esophageal atresia with distal tracheoesophageal fistula", options: ["Pure esophageal atresia", "Esophageal atresia with distal tracheoesophageal fistula", "Proximal fistula only", "H-type fistula"] },
        { q: "Neonate, bilious vomiting, scaphoid abdomen. X-ray: Double bubble sign. Diagnosis?", a: "Duodenal Atresia", options: ["Pyloric Stenosis", "Duodenal Atresia", "Jejunal Atresia", "Malrotation"] },
        { q: "Murphy's Sign is positive in?", a: "Acute Cholecystitis", options: ["Appendicitis", "Acute Cholecystitis", "Pancreatitis", "Renal Colic"] },
        { q: "Most common site for Ca Stomach?", a: "Antrum", options: ["Fundus", "Body", "Antrum", "Cardia"] },
        { q: "Coffee bean sign on X-ray Abdomen?", a: "Sigmoid Volvulus", options: ["Sigmoid Volvulus", "Cecal Volvulus", "Intussusception", "Obstruction"] },
        { q: "MC organ injured in blunt abdominal trauma?", a: "Spleen", options: ["Liver", "Spleen", "Kidney", "Intestine"] },
        { q: "Charcot's Triad (Fever, Jaundice, RUQ Pain) seen in?", a: "Ascending Cholangitis", options: ["Cholecystitis", "Ascending Cholangitis", "Hepatitis", "Pancreatitis"] },
        { q: "Reynolds Pentad adds which two to Charcot's Triad?", a: "Hypotension and Confusion", options: ["Vomiting and Diarrhea", "Hypotension and Confusion", "Pain and Bleeding", "Ascites and Edema"] },
        { q: "Rule of Nines is used for?", a: "Burns BSA estimation", options: ["Trauma score", "Burns BSA estimation", "Dehydration", "Tumor staging"] },
        { q: "Parkland formula for burns fluid resuscitation?", a: "4ml x Kg x %BSA", options: ["2ml x Kg x %BSA", "4ml x Kg x %BSA", "100ml/hr", "3ml x Kg x %BSA"] },
        { q: "Fluid of choice for burns resuscitation?", a: "Ringer Lactate", options: ["Normal Saline", "Ringer Lactate", "Dextrose", "Colloids"] },
        { q: "Most common type of Thyroid Cancer?", a: "Papillary Carcinoma", options: ["Follicular", "Papillary", "Medullary", "Anaplastic"] },
        { q: "Orphan Annie eye nuclei are seen in?", a: "Papillary Thyroid CA", options: ["Follicular", "Papillary", "Medullary", "Anaplastic"] },
        { q: "Psammoma bodies are seen in?", a: "Papillary Thyroid CA", options: ["Follicular", "Papillary", "Medullary", "Anaplastic"] },
        { q: "Medullary Thyroid Carcinoma arises from?", a: "Parafollicular C cells", options: ["Follicular cells", "Parafollicular C cells", "Stromal cells", "Lymphocytes"] },
        { q: "Marker for Medullary Thyroid Carcinoma?", a: "Calcitonin", options: ["Thyroglobulin", "Calcitonin", "CEA", "T3/T4"] },
        { q: "Most common site of breast carcinoma?", a: "Upper Outer Quadrant", options: ["Upper Inner", "Upper Outer", "Lower Inner", "Central"] },
        { q: "Peau d'orange appearance of breast is due to?", a: "Blockage of subdermal lymphatics", options: ["Infection", "Blockage of subdermal lymphatics", "Fat necrosis", "Hematoma"] },
        { q: "Most common benign breast lump in young women?", a: "Fibroadenoma", options: ["Cyst", "Fibroadenoma", "Phyllodes", "Lipoma"] },
        { q: "Most common cause of nipple discharge (bloody)?", a: "Intraductal Papilloma", options: ["Cancer", "Intraductal Papilloma", "Ectasia", "Abscess"] },
        { q: "Triple assessment of breast lump includes?", a: "Clinical exam, Imaging, Biopsy", options: ["History, Exam, Blood test", "Clinical exam, Imaging, Biopsy", "USG, Mammogram, MRI", "None"] },
        { q: "Triangle of Calot boundaries?", a: "Cystic duct, Common Hepatic Duct, Liver margin", options: ["CBD, Cystic duct, Liver", "Cystic duct, Common Hepatic Duct, Liver margin", "Portal vein, Hepatic artery, CBD", "None"] },
        { q: "Content of Calot's triangle?", a: "Cystic Artery", options: ["Hepatic Artery", "Cystic Artery", "Portal Vein", "CBD"] },
        { q: "Courvoisier's Law states?", a: "Palpable gallbladder + Jaundice is unlikely stones", options: ["Palpable GB is stones", "Palpable gallbladder + Jaundice is unlikely stones", "Painful GB is cancer", "None"] },
        { q: "Most common cause of Acute Pancreatitis?", a: "Gallstones", options: ["Alcohol", "Gallstones", "Trauma", "Steroids"] },
        { q: "Cullen's sign (periumbilical ecchymosis) is seen in?", a: "Acute Pancreatitis (Hemorrhagic)", options: ["Appendicitis", "Acute Pancreatitis", "Cholecystitis", "Hernia"] },
        { q: "Grey Turner's sign (flank ecchymosis) is seen in?", a: "Acute Pancreatitis", options: ["Appendicitis", "Acute Pancreatitis", "Peritonitis", "Volvulus"] },
        { q: "Ranson's criteria is used for?", a: "Pancreatitis prognosis", options: ["Appendicitis", "Pancreatitis prognosis", "Cholecystitis", "Trauma"] },
        { q: "Whipple's procedure is done for?", a: "Pancreatic Head Carcinoma", options: ["Tail Ca", "Pancreatic Head Carcinoma", "Splenic rupture", "Gastric Ca"] },
        { q: "McBurney's point tenderness is sign of?", a: "Acute Appendicitis", options: ["Cholecystitis", "Acute Appendicitis", "Diverticulitis", "Pancreatitis"] },
        { q: "Rovsing's sign is?", a: "Pain in RLQ on palpating LLQ", options: ["Pain in RUQ", "Pain in RLQ on palpating LLQ", "Rebound tenderness", "Pain on flexion"] },
        { q: "Most common cause of appendicitis in children?", a: "Lymphoid hyperplasia", options: ["Fecalith", "Lymphoid hyperplasia", "Worms", "Tumor"] },
        { q: "Most common cause of appendicitis in adults?", a: "Fecalith", options: ["Fecalith", "Lymphoid hyperplasia", "Tumor", "Foreign body"] },
        { q: "Carcinoid tumor most commonly arises from?", a: "Appendix (most common site incidentally)", options: ["Ileum", "Appendix", "Rectum", "Stomach"] },
        { q: "Most common site for Carcinoid METASTASIS?", a: "Liver", options: ["Lung", "Liver", "Bone", "Brain"] },
        { q: "Carcinoid syndrome occurs when metastasis is in?", a: "Liver", options: ["Lung", "Liver", "Bone", "Lymph nodes"] },
        { q: "Direct Inguinal Hernia passes through?", a: "Hesselbach's triangle", options: ["Deep ring", "Hesselbach's triangle", "Femoral ring", "Obturator foramen"] },
        { q: "Indirect Inguinal Hernia passes through?", a: "Deep Inguinal Ring", options: ["Hesselbach's triangle", "Deep Inguinal Ring", "Femoral ring", "Lumbar triangle"] },
        { q: "Hesselbach's triangle boundaries?", a: "Inferior epigastric vessels, Rectus sheath, Inguinal ligament", options: ["Femoral vein, Ligament, Muscle", "Inferior epigastric vessels, Rectus sheath, Inguinal ligament", "Sartorius, Adductor, Ligament", "None"] },
        { q: "Femoral hernia is more common in?", a: "Females", options: ["Males", "Females", "Children", "Elderly"] },
        { q: "Most common hernia in females?", a: "Inguinal Hernia (Overall)", options: ["Femoral", "Inguinal Hernia (Overall)", "Umbilical", "Incisional"] },
        { q: "Hernia with highest risk of strangulation?", a: "Femoral Hernia", options: ["Inguinal", "Femoral Hernia", "Umbilical", "Epigastric"] },
        { q: "Lichtenstein repair uses?", a: "Mesh", options: ["Sutures only", "Mesh", "Staples", "Glue"] },
        { q: "Shouldice repair is?", a: "Multi-layer suture repair (No mesh)", options: ["Mesh repair", "Multi-layer suture repair", "Laparoscopic", "Plug repair"] },
        { q: "Goodsall's rule relates to?", a: "Fistula-in-ano", options: ["Hemorrhoids", "Fistula-in-ano", "Fissure", "Abscess"] },
        { q: "Most common site of Anal Fissure?", a: "Posterior midline (6 o'clock)", options: ["Anterior midline", "Posterior midline", "Lateral", "Variable"] },
        { q: "Sentinel pile is associated with?", a: "Chronic Fissure", options: ["Acute Fissure", "Chronic Fissure", "Hemorrhoids", "Fistula"] },
        { q: "Internal hemorrhoids are?", a: "Painless bleeding", options: ["Painful bleeding", "Painless bleeding", "Itching", "Discharge"] },
        { q: "Treatment of grade 1 & 2 hemorrhoids?", a: "Conservative / Banding / Sclerotherapy", options: ["Hemorrhoidectomy", "Conservative / Banding / Sclerotherapy", "Stapling", "Laser"] },
        { q: "Treatment of grade 3 & 4 hemorrhoids?", a: "Hemorrhoidectomy", options: ["Banding", "Sclerotherapy", "Hemorrhoidectomy", "Diet"] },
        { q: "Pilonidal sinus occurs in?", a: "Natal cleft", options: ["Axilla", "Natal cleft", "Groin", "Umbilicus"] },
        { q: "Glasgow Coma Scale (GCS) min and max?", a: "3 and 15", options: ["0 and 15", "3 and 15", "1 and 10", "0 and 10"] },
        { q: "FAST scan is used for?", a: "Trauma (Hemoperitoneum)", options: ["Pregnancy", "Trauma (Hemoperitoneum)", "Gallstones", "Appendicitis"] },
        { q: "Most common organ injured in penetrating trauma?", a: "Small Intestine", options: ["Liver", "Spleen", "Small Intestine", "Colon"] },
        { q: "Triad of Death in Trauma?", a: "Hypothermia, Acidosis, Coagulopathy", options: ["Hypotension, Tachycardia, Tachypnea", "Hypothermia, Acidosis, Coagulopathy", "Pain, Pallor, Pulselessness", "None"] },
        { q: "Tension pneumothorax treatment?", a: "Needle decompression then Chest tube", options: ["Chest tube only", "Needle decompression then Chest tube", "Intubation", "Observation"] },
        { q: "Flail chest is defined as?", a: "Fracture of 3+ ribs in 2+ places", options: ["Fracture of 2 ribs", "Fracture of 3+ ribs in 2+ places", "Sternum fracture", "Lung contusion"] },
        { q: "Paradoxical breathing is seen in?", a: "Flail chest", options: ["Pneumothorax", "Flail chest", "Asthma", "COPD"] },
        { q: "Beck's Triad is for?", a: "Cardiac Tamponade", options: ["Pneumothorax", "Cardiac Tamponade", "Hemothorax", "Embolism"] },
        { q: "Components of Beck's Triad?", a: "Hypotension, Muffled heart sounds, Distended neck veins", options: ["Hypertension, Bradycardia, Irregular breathing", "Hypotension, Muffled heart sounds, Distended neck veins", "Fever, Pain, Rub", "None"] },
        { q: "Hard signs of vascular injury?", a: "Pulsatile bleeding, Expanding hematoma, Thrill/Bruit, Ischemia", options: ["Pain, History of bleed", "Pulsatile bleeding, Expanding hematoma, Thrill/Bruit, Ischemia", "Swelling, Redness", "None"] },
        { q: "Investigation of choice for stable vascular injury?", a: "CT Angiography", options: ["Doppler", "CT Angiography", "DSA", "MRI"] },
        { q: "Compartment syndrome 5 P's?", a: "Pain, Pallor, Paresthesia, Pulselessness, Paralysis", options: ["Pain, Pallor, Pus, Pyrexia, Pruritus", "Pain, Pallor, Paresthesia, Pulselessness, Paralysis", "Polyuria, Polydipsia", "None"] },
        { q: "Earliest sign of Compartment syndrome?", a: "Pain out of proportion to injury / on passive stretch", options: ["Pulselessness", "Pain out of proportion to injury / on passive stretch", "Pallor", "Paralysis"] },
        { q: "Treatment of Compartment syndrome?", a: "Fasciotomy", options: ["Cast", "Fasciotomy", "Elevation", "Analgesics"] },
        { q: "Seminoma of testis is?", a: "Radiosensitive", options: ["Chemo resistant", "Radiosensitive", "Radio resistant", "Benign"] },
        { q: "Most common testicular tumor in children (<3y)?", a: "Yolk Sac Tumor", options: ["Seminoma", "Yolk Sac Tumor", "Teratoma", "Choriocarcinoma"] },
        { q: "Marker for Yolk Sac Tumor?", a: "AFP", options: ["hCG", "AFP", "LDH", "CEA"] },
        { q: "Schiller-Duval bodies are seen in?", a: "Yolk Sac Tumor", options: ["Seminoma", "Yolk Sac Tumor", "Teratoma", "Dysgerminoma"] },
        { q: "Most common testicular tumor in elderly?", a: "Lymphoma", options: ["Seminoma", "Lymphoma", "Leydig cell", "Sertoli cell"] },
        { q: "Renal Cell Carcinoma arises from?", a: "PCT epithelium", options: ["DCT", "PCT epithelium", "Collecting duct", "Loop of Henle"] },
        { q: "Classic triad of RCC?", a: "Hematuria, Flank pain, Mass (Rarely seen together)", options: ["Fever, Pain, Jaundice", "Hematuria, Flank pain, Mass", "Dysuria, Frequency, Urgency", "None"] },
        { q: "Varicocele is most common on?", a: "Left side", options: ["Right side", "Left side", "Bilateral", "Equal"] }
    ]);
}