// FMGE Ultimate Revision - Radiology Module
// Source: MIST RADIOLOGY SUBJECT WISE TEST

if (typeof window.registerSubject === 'function') {
    window.registerSubject('Radiology', [
        { q: "Which statement is false about Mammography?", a: "Popcorn calcification is seen in BIRADS IV lesion", options: ["Sensitivity decreases with dense breast", "Popcorn calcification is seen in BIRADS IV lesion", "Microcalcification is feature of cancer", "MLO view for axillary tail"] },
        { q: "Acute breathlessness after knee surgery. CT shows filling defect. Next step?", a: "CT Pulmonary Angiography", options: ["CT Pulmonary Angiography", "D-dimer", "Duplex Scan", "MR Angiography"] },
        { q: "Neonate with respiratory distress. CXR shows bowel loops in chest (CDH). Contraindicated?", a: "Bag and Mask Ventilation", options: ["Bag and Mask Ventilation", "Gastric decompression", "Cardio-pulmonary Support", "Surgical repair"] },
        { q: "IOC to detect minimal pericardial effusion?", a: "USG", options: ["CT scan", "X Ray", "USG", "MRI"] },
        { q: "Left Heart border on CXR is formed by all except?", a: "Left Atrium", options: ["Aortic knuckle", "Left Atrium", "Left Ventricle", "Pulmonary conus"] },
        { q: "Feature of Pneumothorax on POCUS except?", a: "Presence of seashore sign", options: ["Stratosphere sign", "Barcode sign", "Absence of seashore sign", "Presence of seashore sign"] },
        { q: "Medical device shown in CXR (wire in RA/RV)?", a: "Pacemaker Device", options: ["Pacemaker Device", "Swan Ganz Catheter", "Implantable Defibrillator", "Loop Recorder"] },
        { q: "4yr child, sudden breathlessness, wheezing. CXR shows unilateral hyperinflation. Diagnosis?", a: "Foreign Body Aspiration", options: ["Bronchial Asthma", "Pneumothorax", "Bronchiolitis", "Foreign Body Aspiration"] },
        { q: "Elderly smoker, chronic cough, hemoptysis. CXR shows whiteout with tracheal shift TOWARDS lesion. Cause?", a: "Malignant lung Collapse", options: ["Pneumonectomy", "Malignant lung Collapse", "Diaphragmatic hernia", "Pulmonary Aplasia"] },
        { q: "Snowstorm appearance on USG is seen in?", a: "Hydatidiform Mole", options: ["Ectopic Pregnancy", "Hydatidiform Mole", "Fibroid", "Polyp"] },
        { q: "Spalding sign is seen in?", a: "Intrauterine Death (IUD)", options: ["Live fetus", "IUD", "Twins", "Hydrocephalus"] },
        { q: "Robert's sign is?", a: "Gas in great vessels (IUD)", options: ["Overlap of skull bones", "Gas in great vessels", "Curvature of spine", "None"] },
        { q: "Lambda sign in twin pregnancy indicates?", a: "Dichorionic Diamniotic", options: ["Monochorionic Diamniotic", "Dichorionic Diamniotic", "Monochorionic Monoamniotic", "Conjoined"] },
        { q: "T sign in twin pregnancy indicates?", a: "Monochorionic Diamniotic", options: ["DCDA", "MCDA", "MCMA", "Singleton"] },
        { q: "Banana sign and Lemon sign are seen in?", a: "Spina Bifida (Chiari II)", options: ["Down syndrome", "Spina Bifida", "Anencephaly", "Hydrocephalus"] },
        { q: "Double bubble sign is seen in?", a: "Duodenal Atresia", options: ["Pyloric stenosis", "Duodenal Atresia", "Jejunal atresia", "Malrotation"] },
        { q: "Single bubble sign is seen in?", a: "Pyloric Stenosis / Gastric Volvulus", options: ["Duodenal atresia", "Pyloric Stenosis", "Ileal atresia", "None"] },
        { q: "Triple bubble sign is seen in?", a: "Jejunal Atresia", options: ["Duodenal atresia", "Jejunal Atresia", "Ileal atresia", "Colon atresia"] },
        { q: "Coffee bean sign is seen in?", a: "Sigmoid Volvulus", options: ["Cecal volvulus", "Sigmoid Volvulus", "Intussusception", "Obstruction"] },
        { q: "Coiled spring appearance is seen in?", a: "Intussusception", options: ["Volvulus", "Intussusception", "Obstruction", "Hernia"] },
        { q: "Target sign / Donut sign on USG?", a: "Intussusception", options: ["Appendicitis", "Intussusception", "Pyloric stenosis", "Cholecystitis"] },
        { q: "Bird beak appearance on Barium swallow?", a: "Achalasia Cardia", options: ["Ca Esophagus", "Achalasia Cardia", "Stricture", "Web"] },
        { q: "Rat tail appearance on Barium swallow?", a: "Carcinoma Esophagus", options: ["Achalasia", "Carcinoma Esophagus", "Zenker's", "Hernia"] },
        { q: "Corkscrew esophagus is seen in?", a: "Diffuse Esophageal Spasm", options: ["Achalasia", "DES", "Scleroderma", "Ca Esophagus"] },
        { q: "Lead pipe colon is seen in?", a: "Ulcerative Colitis", options: ["Crohn's", "Ulcerative Colitis", "TB", "Cancer"] },
        { q: "String sign of Kantor is seen in?", a: "Crohn's Disease", options: ["UC", "Crohn's Disease", "TB", "Cancer"] },
        { q: "Saw tooth appearance is seen in?", a: "Diverticulosis", options: ["Polyps", "Diverticulosis", "Cancer", "Colitis"] },
        { q: "Apple core appearance is seen in?", a: "Colorectal Cancer", options: ["Diverticulosis", "Colorectal Cancer", "Volvulus", "Intussusception"] },
        { q: "Thumbprinting on X-ray abdomen?", a: "Ischemic Colitis", options: ["UC", "Ischemic Colitis", "Crohn's", "Obstruction"] },
        { q: "Rigler's sign (Double wall sign) indicates?", a: "Pneumoperitoneum", options: ["Ascites", "Pneumoperitoneum", "Obstruction", "Volvulus"] },
        { q: "Football sign is seen in?", a: "Massive Pneumoperitoneum (Infants)", options: ["Ascites", "Massive Pneumoperitoneum", "Massive Splenomegaly", "Tumor"] },
        { q: "Staghorn calculus is typically composed of?", a: "Struvite (Triple phosphate)", options: ["Calcium oxalate", "Struvite", "Uric acid", "Cystine"] },
        { q: "IOC for renal stones?", a: "NCCT KUB", options: ["USG", "X-ray", "NCCT KUB", "MRI"] },
        { q: "Putty kidney is seen in?", a: "Renal Tuberculosis", options: ["Renal cell carcinoma", "Renal Tuberculosis", "Polycystic kidney", "Hydronephrosis"] },
        { q: "Drooping lily sign is seen in?", a: "Duplex collecting system", options: ["Ectopic kidney", "Duplex collecting system", "Horseshoe kidney", "PUJ obstruction"] },
        { q: "Cobra head sign is seen in?", a: "Ureterocele", options: ["Stricture", "Ureterocele", "Stone", "Tumor"] },
        { q: "Mickey mouse sign (Pelvis) is seen in?", a: "Ureteropelvic Junction Obstruction (or Vein/Artery relationship)", options: ["VUR", "PUJ Obstruction", "Calculus", "Tumor"] },
        { q: "Flower vase appearance of ureters?", a: "Horseshoe kidney", options: ["Duplex", "Horseshoe kidney", "Ectopic", "Polycystic"] },
        { q: "Sunburst appearance on X-ray bone?", a: "Osteosarcoma", options: ["Ewing's sarcoma", "Osteosarcoma", "Chondrosarcoma", "Osteoclastoma"] },
        { q: "Codman's triangle is seen in?", a: "Osteosarcoma", options: ["Ewing's", "Osteosarcoma", "Giant cell tumor", "Osteoid osteoma"] },
        { q: "Onion peel appearance is seen in?", a: "Ewing's Sarcoma", options: ["Osteosarcoma", "Ewing's Sarcoma", "Chondrosarcoma", "Osteomyelitis"] },
        { q: "Soap bubble appearance is seen in?", a: "Giant Cell Tumor (Osteoclastoma)", options: ["Osteosarcoma", "Giant Cell Tumor", "Bone cyst", "Fibrous dysplasia"] },
        { q: "Fallen fragment sign is seen in?", a: "Simple Bone Cyst", options: ["ABC", "Simple Bone Cyst", "GCT", "Chondroblastoma"] },
        { q: "Shepherd's crook deformity is seen in?", a: "Fibrous Dysplasia", options: ["Paget's", "Fibrous Dysplasia", "Rickets", "Osteogenesis Imperfecta"] },
        { q: "Cotton wool appearance of skull?", a: "Paget's Disease", options: ["Myeloma", "Paget's Disease", "Metastasis", "Fibrous dysplasia"] },
        { q: "Punched out lytic lesions in skull?", a: "Multiple Myeloma", options: ["Paget's", "Multiple Myeloma", "Metastasis", "Thalassemia"] },
        { q: "Hair on end appearance is seen in?", a: "Thalassemia", options: ["Iron deficiency", "Thalassemia", "Sickle cell", "Spherocytosis"] },
        { q: "Bamboo spine is seen in?", a: "Ankylosing Spondylitis", options: ["RA", "Ankylosing Spondylitis", "OA", "TB Spine"] },
        { q: "Pencil in cup deformity?", a: "Psoriatic Arthritis", options: ["RA", "Psoriatic Arthritis", "OA", "Gout"] },
        { q: "Rat bite erosion?", a: "Gout", options: ["RA", "Gout", "OA", "Psoriatic"] }
    ]);
}