// FMGE Ultimate Revision - Pharmacology Module
// Source: MIST SUBJECT WISE TEST PHARMACOLOGY (27th Nov 2025)

if (typeof window.registerSubject === 'function') {
    window.registerSubject('Pharmacology', [
        { q: "A patient with blood pressure 148/92 mmHg and chronic kidney disease with proteinuria. Appropriate antihypertensive?", a: "Telmisartan", options: ["Telmisartan", "Spironolactone", "Amlodipine", "Metoprolol"] },
        { q: "27F with irregular heartbeat, weight loss, heat intolerance. Medication started?", a: "Methimazole", options: ["Propranolol", "Lorazepam", "Methimazole", "Amiodarone"] },
        { q: "64M with exertional chest pain, aspirin causes wheezing. Suitable alternative?", a: "Clopidogrel", options: ["Heparin", "Warfarin", "Clopidogrel", "Streptokinase"] },
        { q: "Mechanism of action of Sulfonylureas is:", a: "Inhibit ATP sensitive K+ channels", options: ["Inhibit ATP sensitive K+ channels", "Increase PPAR-y activity", "Inhibit a-glucosidase", "SGLT-2 inhibitors"] },
        { q: "Hypertension on 3 drugs, BP still poorly controlled. What is the next step (Resistant HTN)?", a: "Add Spironolactone", // Implied from standard guidelines for resistant HTN
          options: ["Add Spironolactone", "Increase dose of ACEI", "Add Beta blocker", "Stop all drugs"] }, 
        { q: "Drug of choice for MRSA?", a: "Vancomycin", options: ["Amoxicillin", "Ceftriaxone", "Vancomycin", "Azithromycin"] },
        { q: "Which drug causes Red-Green color blindness?", a: "Ethambutol", options: ["Isoniazid", "Rifampicin", "Ethambutol", "Pyrazinamide"] },
        { q: "Antidote for Paracetamol poisoning?", a: "N-Acetylcysteine", options: ["Atropine", "N-Acetylcysteine", "Flumazenil", "Naloxone"] },
        { q: "Drug of choice for Scrub Typhus?", a: "Doxycycline", options: ["Penicillin", "Doxycycline", "Ceftriaxone", "Metronidazole"] },
        { q: "DOC for hyperthyroidism in 1st trimester pregnancy?", a: "Propylthiouracil (PTU)", options: ["Methimazole", "Propylthiouracil (PTU)", "Carbimazole", "Radioactive Iodine"] },
        { q: "Side effect of ACE inhibitors?", a: "Dry Cough", options: ["Dry Cough", "Hypokalemia", "Hyperglycemia", "Tachycardia"] },
        { q: "Mechanism of action of Aspirin?", a: "Irreversible COX inhibition", options: ["Reversible COX inhibition", "Irreversible COX inhibition", "Lipoxygenase inhibition", "Phospholipase inhibition"] },
        { q: "Drug used for closure of Patent Ductus Arteriosus (PDA)?", a: "Indomethacin", options: ["PGE1", "Indomethacin", "Digoxin", "Dopamine"] },
        { q: "Drug used to keep PDA open?", a: "Alprostadil (PGE1)", options: ["Indomethacin", "Ibuprofen", "Alprostadil (PGE1)", "Aspirin"] },
        { q: "Mechanism of action of Digoxin?", a: "Na+/K+ ATPase inhibition", options: ["Beta stimulation", "Na+/K+ ATPase inhibition", "Calcium channel blockade", "PDE inhibition"] },
        { q: "Side effect of Digoxin toxicity?", a: "Yellow vision (Xanthopsia)", options: ["Blue vision", "Red vision", "Yellow vision (Xanthopsia)", "Blindness"] },
        { q: "Antidote for Digoxin toxicity?", a: "Digibind (Digoxin immune Fab)", options: ["Atropine", "Lignocaine", "Digibind", "Potassium"] },
        { q: "Class I antiarrhythmics block which channels?", a: "Sodium channels", options: ["Sodium channels", "Beta receptors", "Potassium channels", "Calcium channels"] },
        { q: "Adenosine is the drug of choice for?", a: "PSVT", options: ["Atrial Fibrillation", "PSVT", "Ventricular Tachycardia", "Bradycardia"] },
        { q: "Drug of choice for Ventricular Tachycardia?", a: "Lignocaine / Amiodarone", options: ["Digoxin", "Verapamil", "Lignocaine / Amiodarone", "Adenosine"] },
        { q: "Side effect of Amiodarone?", a: "Thyroid dysfunction / Pulmonary fibrosis", options: ["Gingival hyperplasia", "Thyroid dysfunction / Pulmonary fibrosis", "Lupus like syndrome", "Dry cough"] },
        { q: "Drug causing Gingival Hyperplasia?", a: "Phenytoin / Cyclosporine / Nifedipine", options: ["Phenytoin", "Carbamazepine", "Valproate", "Ethosuximide"] },
        { q: "Drug of choice for absence seizures?", a: "Ethosuximide", options: ["Phenytoin", "Carbamazepine", "Ethosuximide", "Phenobarbitone"] },
        { q: "Drug of choice for status epilepticus?", a: "Lorazepam (IV)", options: ["Phenytoin", "Valproate", "Lorazepam (IV)", "Propofol"] },
        { q: "Teratogenic effect of Valproate?", a: "Neural tube defects", options: ["Ebstein anomaly", "Neural tube defects", "Phocomelia", "Cleft lip"] },
        { q: "Teratogenic effect of Lithium?", a: "Ebstein anomaly", options: ["Neural tube defects", "Ebstein anomaly", "Renal agenesis", "Gray baby syndrome"] },
        { q: "Mechanism of action of Benzodiazepines?", a: "Increase frequency of Cl- channel opening (GABA-A)", options: ["Increase duration of Cl- opening", "Increase frequency of Cl- opening", "Block Na+ channels", "Block Ca2+ channels"] },
        { q: "Mechanism of action of Barbiturates?", a: "Increase duration of Cl- channel opening", options: ["Increase frequency of Cl- opening", "Increase duration of Cl- opening", "Block NMDA", "Stimulate 5HT"] },
        { q: "Antidote for Benzodiazepine overdose?", a: "Flumazenil", options: ["Naloxone", "Flumazenil", "N-acetylcysteine", "Protamine"] },
        { q: "Antidote for Opioid overdose?", a: "Naloxone", options: ["Naltrexone", "Naloxone", "Methadone", "Buprenorphine"] },
        { q: "Drug used for Opioid dependence maintenance?", a: "Methadone / Buprenorphine", options: ["Naloxone", "Methadone / Buprenorphine", "Morphine", "Codeine"] },
        { q: "Mechanism of action of Heparin?", a: "Activates Antithrombin III", options: ["Inhibits Vit K epoxide reductase", "Activates Antithrombin III", "Direct Thrombin Inhibitor", "Antiplatelet"] },
        { q: "Antidote for Heparin?", a: "Protamine Sulfate", options: ["Vit K", "FFP", "Protamine Sulfate", "Idarucizumab"] },
        { q: "Mechanism of action of Warfarin?", a: "Inhibits Vit K epoxide reductase", options: ["Activates Antithrombin III", "Inhibits Vit K epoxide reductase", "Direct Factor Xa inhibitor", "Antiplatelet"] },
        { q: "Antidote for Warfarin?", a: "Vitamin K / FFP", options: ["Protamine", "Vitamin K / FFP", "Andexanet alfa", "Idarucizumab"] },
        { q: "Drug of choice for Heparin Induced Thrombocytopenia (HIT)?", a: "Argatroban / Lepirudin", options: ["Warfarin", "LMWH", "Argatroban / Lepirudin", "Aspirin"] },
        { q: "Thrombolytic drug mechanism?", a: "Converts Plasminogen to Plasmin", options: ["Inhibits Thrombin", "Inhibits Xa", "Converts Plasminogen to Plasmin", "Blocks ADP receptor"] },
        { q: "Mechanism of action of Omeprazole?", a: "H+/K+ ATPase inhibitor (Proton Pump Inhibitor)", options: ["H2 blocker", "H+/K+ ATPase inhibitor", "Prostaglandin analogue", "Antacid"] },
        { q: "Side effect of long term PPI use?", a: "B12 deficiency / Osteoporosis / C. diff infection", options: ["Gynecomastia", "B12 deficiency / Osteoporosis", "Dry mouth", "Extrapyramidal symptoms"] },
        { q: "Drug used for NSAID induced ulcer prophylaxis?", a: "Misoprostol", options: ["Sucralfate", "Misoprostol", "Bismuth", "Aluminium hydroxide"] },
        { q: "Mechanism of action of Ondansetron?", a: "5-HT3 antagonist", options: ["D2 antagonist", "5-HT3 antagonist", "H1 antagonist", "NK1 antagonist"] },
        { q: "Mechanism of action of Metoclopramide?", a: "D2 antagonist + 5-HT4 agonist", options: ["5-HT3 antagonist", "D2 antagonist + 5-HT4 agonist", "Muscarinic antagonist", "H1 antagonist"] },
        { q: "Side effect of Metoclopramide?", a: "Extrapyramidal symptoms (Dystonia)", options: ["Diarrhea", "Extrapyramidal symptoms", "Constipation", "Dry mouth"] },
        { q: "Drug of choice for chemotherapy induced vomiting (Highly emetogenic)?", a: "Aprepitant + 5HT3 antag + Dexamethasone", options: ["Metoclopramide", "Ondansetron alone", "Aprepitant + 5HT3 + Dexa", "Promethazine"] },
        { q: "Mechanism of action of Statins?", a: "HMG-CoA reductase inhibitors", options: ["PPAR-alpha activator", "HMG-CoA reductase inhibitors", "Bile acid sequestrant", "Cholesterol absorption inhibitor"] },
        { q: "Major side effect of Statins?", a: "Myopathy / Rhabdomyolysis", options: ["Flushing", "Myopathy / Rhabdomyolysis", "Gout", "Hypertension"] },
        { q: "Drug causing Red Man Syndrome?", a: "Vancomycin", options: ["Rifampicin", "Vancomycin", "Linezolid", "Amphotericin B"] },
        { q: "Mechanism of Red Man Syndrome?", a: "Histamine release (Non-IgE mediated)", options: ["IgE mediated allergy", "Histamine release (Non-IgE)", "Direct toxicity", "Vasculitis"] },
        { q: "Mechanism of action of Fluoroquinolones?", a: "Inhibit DNA Gyrase (Topoisomerase II/IV)", options: ["Inhibit Cell wall synthesis", "Inhibit DNA Gyrase", "Inhibit 30S ribosome", "Inhibit 50S ribosome"] },
        { q: "Side effect of Fluoroquinolones?", a: "Tendinitis / Tendon rupture", options: ["Nephrotoxicity", "Ototoxicity", "Tendinitis / Tendon rupture", "Red man syndrome"] },
        { q: "Mechanism of action of Tetracyclines?", a: "Inhibit 30S ribosome", options: ["Inhibit 50S ribosome", "Inhibit 30S ribosome", "Inhibit cell wall", "Inhibit DNA gyrase"] },
        { q: "Side effect of Tetracyclines?", a: "Teeth discoloration / Bone growth inhibition", options: ["Ototoxicity", "Teeth discoloration", "Red man syndrome", "Gray baby syndrome"] },
        { q: "Drug causing Gray Baby Syndrome?", a: "Chloramphenicol", options: ["Tetracycline", "Chloramphenicol", "Vancomycin", "Sulfonamides"] },
        { q: "Mechanism of action of Aminoglycosides?", a: "Inhibit 30S ribosome (Bactericidal)", options: ["Inhibit 50S ribosome", "Inhibit 30S ribosome (Bactericidal)", "Inhibit cell wall", "Inhibit folic acid"] },
        { q: "Side effects of Aminoglycosides?", a: "Nephrotoxicity and Ototoxicity", options: ["Hepatotoxicity", "Nephrotoxicity and Ototoxicity", "Bone marrow suppression", "Pulmonary fibrosis"] },
        { q: "Drug of choice for Syphilis?", a: "Benzathine Penicillin G", options: ["Doxycycline", "Benzathine Penicillin G", "Azithromycin", "Ceftriaxone"] },
        { q: "Jarisch-Herxheimer reaction is seen in treatment of?", a: "Syphilis", options: ["Gonorrhea", "Syphilis", "Chlamydia", "TB"] },
        { q: "Drug of choice for Gonorrhea?", a: "Ceftriaxone", options: ["Penicillin", "Ceftriaxone", "Doxycycline", "Ciprofloxacin"] },
        { q: "Drug of choice for Chlamydia?", a: "Azithromycin / Doxycycline", options: ["Penicillin", "Azithromycin / Doxycycline", "Metronidazole", "Cefixime"] },
        { q: "Mechanism of action of Isoniazid?", a: "Inhibits Mycolic acid synthesis", options: ["Inhibits RNA polymerase", "Inhibits Mycolic acid synthesis", "Inhibits Arabinosyl transferase", "Inhibits ATP synthase"] },
        { q: "Side effect of Isoniazid?", a: "Peripheral Neuropathy / Hepatotoxicity", options: ["Optic Neuritis", "Peripheral Neuropathy / Hepatotoxicity", "Orange urine", "Hyperuricemia"] },
        { q: "Vitamin given with Isoniazid to prevent neuropathy?", a: "Pyridoxine (B6)", options: ["Thiamine", "Pyridoxine (B6)", "Cobalamin", "Niacin"] },
        { q: "Mechanism of action of Rifampicin?", a: "Inhibits DNA dependent RNA polymerase", options: ["Inhibits Mycolic acid", "Inhibits RNA polymerase", "Inhibits Cell wall", "Inhibits 30S ribosome"] },
        { q: "Side effect of Rifampicin?", a: "Orange discoloration of body fluids / Hepatotoxicity", options: ["Optic neuritis", "Orange discoloration of body fluids", "Hyperuricemia", "Ototoxicity"] },
        { q: "Side effect of Pyrazinamide?", a: "Hyperuricemia (Gout) / Hepatotoxicity", options: ["Peripheral neuropathy", "Hyperuricemia (Gout)", "Optic neuritis", "Ototoxicity"] },
        { q: "Side effect of Ethambutol?", a: "Optic Neuritis (Color blindness)", options: ["Hepatotoxicity", "Optic Neuritis", "Nephrotoxicity", "Gout"] },
        { q: "Drug of choice for Invasive Aspergillosis?", a: "Voriconazole", options: ["Amphotericin B", "Fluconazole", "Voriconazole", "Caspofungin"] },
        { q: "Mechanism of action of Amphotericin B?", a: "Binds to Ergosterol and forms pores", options: ["Inhibits Ergosterol synthesis", "Binds to Ergosterol and forms pores", "Inhibits Glucan synthesis", "Inhibits Microtubules"] },
        { q: "Side effect of Amphotericin B?", a: "Nephrotoxicity / Hypokalemia", options: ["Hepatotoxicity", "Nephrotoxicity / Hypokalemia", "Bone marrow suppression", "Ototoxicity"] },
        { q: "Mechanism of action of Azoles (Fluconazole)?", a: "Inhibit 14-alpha demethylase (Ergosterol synthesis)", options: ["Bind Ergosterol", "Inhibit 14-alpha demethylase", "Inhibit Squalene epoxidase", "Inhibit Thymidylate synthase"] },
        { q: "Drug of choice for Onychomycosis?", a: "Terbinafine", options: ["Griseofulvin", "Terbinafine", "Nystatin", "Ketoconazole"] },
        { q: "Mechanism of action of Metronidazole?", a: "Free radical generation (DNA damage)", options: ["Inhibit cell wall", "Free radical generation", "Inhibit protein synthesis", "Inhibit folic acid"] },
        { q: "Side effect of Metronidazole?", a: "Metallic taste / Disulfiram like reaction", options: ["Red man syndrome", "Metallic taste / Disulfiram like reaction", "Nephrotoxicity", "Ototoxicity"] },
        { q: "Drug of choice for Malaria (Chloroquine sensitive)?", a: "Chloroquine", options: ["Artemisinin", "Chloroquine", "Quinine", "Primaquine"] },
        { q: "Drug for radical cure of Vivax malaria (Hypnozoites)?", a: "Primaquine", options: ["Chloroquine", "Primaquine", "Mefloquine", "Doxycycline"] },
        { q: "Contraindication for Primaquine?", a: "G6PD Deficiency", options: ["Pregnancy", "G6PD Deficiency", "Renal failure", "Liver failure"] },
        { q: "Drug of choice for Falciparum malaria (Severe)?", a: "IV Artesunate", options: ["Oral Chloroquine", "IV Artesunate", "IV Quinine", "Mefloquine"] },
        { q: "Mechanism of action of Methotrexate?", a: "Dihydrofolate reductase inhibitor", options: ["Thymidylate synthase inhibitor", "Dihydrofolate reductase inhibitor", "Alkylating agent", "Microtubule inhibitor"] },
        { q: "Rescue agent for Methotrexate toxicity?", a: "Leucovorin (Folinic acid)", options: ["Folic acid", "Leucovorin (Folinic acid)", "Mesna", "Dexrazoxane"] },
        { q: "Side effect of Cyclophosphamide?", a: "Hemorrhagic Cystitis", options: ["Pulmonary fibrosis", "Hemorrhagic Cystitis", "Cardiotoxicity", "Peripheral neuropathy"] },
        { q: "Drug to prevent Hemorrhagic Cystitis?", a: "Mesna", options: ["Leucovorin", "Mesna", "Amifostine", "Filgrastim"] },
        { q: "Side effect of Doxorubicin?", a: "Dilated Cardiomyopathy", options: ["Pulmonary fibrosis", "Dilated Cardiomyopathy", "Nephrotoxicity", "Hemorrhagic cystitis"] },
        { q: "Side effect of Bleomycin?", a: "Pulmonary Fibrosis", options: ["Cardiotoxicity", "Pulmonary Fibrosis", "Nephrotoxicity", "Bone marrow suppression"] },
        { q: "Side effect of Vincristine?", a: "Peripheral Neuropathy", options: ["Bone marrow suppression", "Peripheral Neuropathy", "Hemorrhagic cystitis", "Cardiotoxicity"] },
        { q: "Mechanism of action of Paclitaxel?", a: "Stabilizes microtubules (prevents breakdown)", options: ["Inhibits microtubule formation", "Stabilizes microtubules", "Alkylating agent", "Antimetabolite"] },
        { q: "Monoclonal antibody against HER2/neu?", a: "Trastuzumab", options: ["Rituximab", "Trastuzumab", "Bevacizumab", "Infliximab"] },
        { q: "Monoclonal antibody against CD20?", a: "Rituximab", options: ["Trastuzumab", "Rituximab", "Cetuximab", "Alemtuzumab"] },
        { q: "Monoclonal antibody against VEGF?", a: "Bevacizumab", options: ["Rituximab", "Bevacizumab", "Infliximab", "Adalimumab"] },
        { q: "Drug used for Rheumatoid Arthritis (DMARD of choice)?", a: "Methotrexate", options: ["Sulfasalazine", "Methotrexate", "Hydroxychloroquine", "Leflunomide"] },
        { q: "Side effect of Hydroxychloroquine?", a: "Retinopathy (Bull's eye maculopathy)", options: ["Nephrotoxicity", "Retinopathy", "Hepatotoxicity", "Pulmonary fibrosis"] },
        { q: "Drug of choice for acute gout?", a: "NSAIDs", options: ["Allopurinol", "NSAIDs", "Probenecid", "Febuxostat"] },
        { q: "Drug of choice for chronic gout (Urate lowering)?", a: "Allopurinol", options: ["Colchicine", "Allopurinol", "Indomethacin", "Steroids"] },
        { q: "Mechanism of action of Allopurinol?", a: "Xanthine Oxidase Inhibitor", options: ["Increases uric acid excretion", "Xanthine Oxidase Inhibitor", "Inhibits microtubule polymerization", "Inhibits COX"] },
        { q: "Mechanism of action of Colchicine?", a: "Inhibits microtubule polymerization", options: ["Xanthine oxidase inhibitor", "Inhibits microtubule polymerization", "Inhibits COX", "Uricosuric"] },
        { q: "Drug used for PDA closure?", a: "Indomethacin", options: ["Prostaglandin", "Indomethacin", "Paracetamol", "Aspirin"] },
        { q: "Antidote for Iron poisoning?", a: "Deferoxamine", options: ["Penicillamine", "Deferoxamine", "Dimercaprol", "EDTA"] },
        { q: "Antidote for Copper poisoning (Wilson's)?", a: "Penicillamine", options: ["Deferoxamine", "Penicillamine", "N-acetylcysteine", "Protamine"] },
        { q: "Antidote for Lead poisoning?", a: "CaNa2EDTA / Dimercaprol", options: ["Deferoxamine", "CaNa2EDTA", "Flumazenil", "Atropine"] },
        { q: "Antidote for Organophosphate poisoning?", a: "Atropine + Pralidoxime", options: ["Physostigmine", "Atropine + Pralidoxime", "Naloxone", "Flumazenil"] },
        { q: "Antidote for Atropine poisoning?", a: "Physostigmine", options: ["Pralidoxime", "Physostigmine", "Atropine", "Pilocarpine"] }
    ]);
}