if (typeof window.registerSubject === 'function') {
    window.registerSubject('PSM', [
        { q: "On occasion of children day 14th Nov, a camp was organised in Govt Public school where 500 children in age group of 5-15 years were examined to look for any deficiency symptoms of Vitamin A, level of screening:", a: "Secondary", options: ["Primordial", "Primary", "Secondary", "Tertiary"] },
        { q: "As a part of active malaria surveillance MPW-M is doing regular insecticidal spray, level of prevention:", a: "Primary specific", options: ["Primordial", "Primary specific", "Primary health promotion", "Secondary"] },
        { q: "After diagnosis of type 1 diabetes in 15year old child in family, a rule was made for all children to play football daily for 60 minutes before meal, level of prevention:", a: "Primordial", options: ["Primordial", "Primary", "Secondary", "Tertiary"] },
        { q: "A splint applied to a 25year old man after road traffic accident to prevent future disability as given in image, level of prevention:", a: "Tertiary", options: ["Primordial", "Primary", "Secondary", "Tertiary"] },
        { q: "It is mandatory to fill column of 'Order of birth' in reporting:", a: "Live birth", options: ["Live birth", "Still birth", "Marriage", "Death"] },
        { q: "All are true about herd immunity except:", a: "It is good for all diseases", options: ["It depends upon the immunization status of the population", "It protects the unimmunized", "It is good for all diseases", "Determined by secondary attack rate"] },
        { q: "Denominator in calculating infant mortality rate:", a: "Total live birth in same year", options: ["Total birth in same year", "Total live birth in same year", "Total pregnancies", "Mid year population"] },
        { q: "Calculate general fertility rate, if total live births are 5000, mid year female population of 15-49 years is 25000 and total mid year population is 50000?", a: "200", options: ["50", "200", "100", "250"] },
        { q: "Best index for burden of disease:", a: "DALY", options: ["Case fatality rate", "Disability rate", "DALY", "Dependency ratio"] },
        { q: "Calculate pearl index if 50 women using OCP for 2 years and 5 accidental pregnancies occurred:", a: "5", options: ["2.5", "5", "10", "20"] },
        { q: "A person eating popcorn in cinema hall choked on it and died, mode of death:", a: "Accidental", options: ["Syncope", "Coma", "Asphyxia", "Accidental"] },
        { q: "Humane slaughter technique is:", a: "Stunning by electricity", options: ["Pithing", "Stunning by electricity", "CO2 anesthesia", "Captive bolt"] },
        { q: "Most common cause of blindness in India?", a: "Cataract", options: ["Glaucoma", "Refractive error", "Cataract", "Vitamin A deficiency"] },
        { q: "Best indicator of availability of health services:", a: "Doctor population ratio", options: ["Nurse population ratio", "Doctor population ratio", "Hospital bed population ratio", "Patient doctor ratio"] },
        { q: "Mosquito shown in image is vector for (Aedes - white stripes)?", a: "Dengue", options: ["Malaria", "Filaria", "Dengue", "Japanese Encephalitis"] },
        { q: "In a village of 1000 population, 200 cases of diabetes were present in Jan 2024. 50 new cases appeared in 2024. Calculate incidence:", a: "62.5 per 1000", options: ["50 per 1000", "250 per 1000", "62.5 per 1000", "200 per 1000"] },
        { q: "Identify the image (Copper T 380A):", a: "Cu T 380A", options: ["Lippes loop", "Cu T 380A", "Nova T", "Mirena"] },
        { q: "Effective life of Cu T 380A:", a: "10 years", options: ["3 years", "5 years", "10 years", "15 years"] },
        { q: "A specific screening test has 90% sensitivity and 90% specificity. Prevalence is 1%. Calculate Positive Predictive Value:", a: "8.3%", options: ["90%", "8.3%", "1%", "50%"] },
        { q: "Vaccine vial monitor (VVM) is based on:", a: "Time and temperature", options: ["Time only", "Temperature only", "Time and temperature", "Humidity"] },
        { q: "Colour of bag for disposal of placenta?", a: "Yellow", options: ["Red", "Yellow", "Blue", "White"] },
        { q: "Epidemic dropsy is caused by?", a: "Argemone oil", options: ["Mustard oil", "Argemone oil", "Khesari dal", "Aflatoxin"] },
        { q: "Specific protection is?", a: "Primary prevention", options: ["Primordial", "Primary prevention", "Secondary", "Tertiary"] },
        { q: "Best study to determine rare disease?", a: "Case control", options: ["Cohort", "Case control", "Cross sectional", "RCT"] },
        { q: "Best study to determine incidence?", a: "Cohort", options: ["Case control", "Cohort", "Cross sectional", "Ecological"] },
        { q: "Which of the following is NOT a live vaccine?", a: "Salk (IPV)", options: ["BCG", "OPV (Sabin)", "Salk (IPV)", "Measles"] },
        { q: "Route of administration of BCG vaccine?", a: "Intradermal", options: ["Subcutaneous", "Intradermal", "Intramuscular", "Oral"] },
        { q: "Dose of Vitamin A at 9 months?", a: "1 lakh IU", options: ["50,000 IU", "1 lakh IU", "2 lakh IU", "5 lakh IU"] },
        { q: "Most common side effect of IUD?", a: "Bleeding", options: ["Pain", "Bleeding", "Perforation", "Infection"] },
        { q: "Identify the symbol (Biohazard):", a: "Biohazard", options: ["Radiation", "Biohazard", "Cytotoxic", "Recycle"] },
        { q: "Disability Adjusted Life Years (DALY) is sum of?", a: "YLL + YLD", options: ["YLL - YLD", "YLL + YLD", "YLL * YLD", "Life expectancy - YLL"] },
        { q: "Target for Iodine deficiency control?", a: "Prevalence < 5%", options: ["< 1%", "< 5%", "< 10%", "Zero"] },
        { q: "Most common cancer in males in India?", a: "Oral cancer", options: ["Lung", "Oral cancer", "Prostate", "Stomach"] },
        { q: "Most common cancer in females in India?", a: "Breast cancer", options: ["Cervix", "Breast cancer", "Ovary", "Lung"] },
        { q: "Iceberg phenomenon of disease differentiates?", a: "Apparent and inapparent cases", options: ["Symptomatic and asymptomatic", "Apparent and inapparent cases", "Severe and mild", "Diagnosed and undiagnosed"] },
        { q: "Floating tip of iceberg represents?", a: "Diagnosed cases", options: ["Undiagnosed", "Diagnosed cases", "Carriers", "Latent"] },
        { q: "Submerged portion of iceberg represents?", a: "Undiagnosed / Carriers / Latent", options: ["Clinical cases", "Undiagnosed / Carriers / Latent", "Dead", "Cured"] },
        { q: "Which disease does NOT show iceberg phenomenon?", a: "Rabies / Measles / Tetanus", options: ["Polio", "Hepatitis", "Rabies / Measles / Tetanus", "Cholera"] },
        { q: "Serial interval is?", a: "Time between primary and secondary case onset", options: ["Time between infection and symptoms", "Time between primary and secondary case onset", "Time of communicability", "None"] },
        { q: "Generation time is roughly equal to?", a: "Serial interval", options: ["Incubation period", "Serial interval", "Communicable period", "Latent period"] },
        { q: "Index case is?", a: "First case coming to attention of investigator", options: ["First case in population", "First case coming to attention of investigator", "Secondary case", "Carrier"] },
        { q: "Primary case is?", a: "First case introduced in population", options: ["First case reported", "First case introduced in population", "Contact case", "None"] },
        { q: "Quarantine is applied to?", a: "Healthy contacts", options: ["Infected persons", "Healthy contacts", "Animals", "Vectors"] },
        { q: "Isolation is applied to?", a: "Infected cases", options: ["Healthy contacts", "Infected cases", "Suspects", "Travelers"] },
        { q: "Sentinel surveillance is for?", a: "Missing cases / Hidden burden", options: ["Total cases", "Missing cases / Hidden burden", "Deaths", "Cure rate"] },
        { q: "Hard water contains?", a: "Calcium and Magnesium", options: ["Sodium", "Potassium", "Calcium and Magnesium", "Iron"] },
        { q: "Temporary hardness is due to?", a: "Bicarbonates", options: ["Sulfates", "Chlorides", "Bicarbonates", "Nitrates"] },
        { q: "Permanent hardness is due to?", a: "Chlorides and Sulfates", options: ["Bicarbonates", "Carbonates", "Chlorides and Sulfates", "Oxides"] },
        { q: "Orthotolidine test measures?", a: "Free and Combined Chlorine", options: ["Free Chlorine only", "Combined only", "Free and Combined Chlorine", "pH"] },
        { q: "Horrock's apparatus is used for?", a: "Chlorine demand", options: ["Chlorine dose", "Chlorine demand", "Residual chlorine", "Turbidity"] },
        { q: "Recommended level of free residual chlorine in drinking water?", a: "0.5 mg/L for 1 hour", options: ["0.2 mg/L", "0.5 mg/L for 1 hour", "1 mg/L", "2 mg/L"] },
        { q: "Kata thermometer measures?", a: "Cooling power of air", options: ["Temperature", "Humidity", "Cooling power of air", "Air velocity"] },
        { q: "Sling psychrometer measures?", a: "Humidity", options: ["Temperature", "Humidity", "Radiation", "Pressure"] },
        { q: "Best method of refuse disposal for hospitals?", a: "Incineration", options: ["Dumping", "Composting", "Incineration", "Burial"] },
        { q: "Septic tank works on principle of?", a: "Anaerobic digestion", options: ["Aerobic", "Anaerobic digestion", "Chemical", "Mechanical"] },
        { q: "Mosquito biting at night?", a: "Culex / Anopheles", options: ["Aedes (Day)", "Culex / Anopheles", "Mansonia", "None"] },
        { q: "Tiger mosquito is?", a: "Aedes", options: ["Anopheles", "Culex", "Aedes", "Mansonia"] },
        { q: "Guppy fish is used for control of?", a: "Mosquito larvae", options: ["Cyclops", "Mosquito larvae", "Snails", "Flies"] },
        { q: "Zinc deficiency causes?", a: "Acrodermatitis enteropathica", options: ["Goiter", "Anemia", "Acrodermatitis enteropathica", "Scurvy"] },
        { q: "Iodine deficiency causes?", a: "Goiter / Cretinism", options: ["Rickets", "Goiter / Cretinism", "Beriberi", "Pellagra"] },
        { q: "Fluorosis affects?", a: "Teeth and Bones", options: ["Liver", "Kidney", "Teeth and Bones", "Brain"] },
        { q: "Nalgonda technique is for?", a: "Defluoridation", options: ["Chlorination", "Defluoridation", "Desalination", "Filtration"] },
        { q: "Mid Day Meal provides?", a: "1/3rd calorie and 1/2 protein requirement", options: ["1/2 calorie", "1/3rd calorie and 1/2 protein requirement", "Full requirement", "1/4th calorie"] },
        { q: "Vitamin B1 (Thiamine) deficiency causes?", a: "Beriberi / Wernicke's", options: ["Pellagra", "Scurvy", "Beriberi / Wernicke's", "Rickets"] },
        { q: "Niacin deficiency causes?", a: "Pellagra", options: ["Beriberi", "Pellagra", "Anemia", "Night blindness"] },
        { q: "Vitamin C deficiency causes?", a: "Scurvy", options: ["Rickets", "Scurvy", "Beriberi", "Pellagra"] },
        { q: "Sensitivity formula?", a: "TP / (TP + FN) * 100", options: ["TN / (TN + FP)", "TP / (TP + FN) * 100", "TP / (TP + FP)", "TN / (TN + FN)"] },
        { q: "Specificity formula?", a: "TN / (TN + FP) * 100", options: ["TP / (TP + FN)", "TN / (TN + FP) * 100", "TP / (TP + FP)", "TN / (TN + FN)"] },
        { q: "Positive Predictive Value depends heavily on?", a: "Prevalence", options: ["Sensitivity", "Specificity", "Prevalence", "Incidence"] },
        { q: "Attributable Risk indicates?", a: "How much disease is attributed to exposure", options: ["Strength of association", "How much disease is attributed to exposure", "Incidence", "Prevalence"] },
        { q: "Relative Risk is calculated in?", a: "Cohort study", options: ["Case control", "Cohort study", "Cross sectional", "Ecological"] },
        { q: "Odds Ratio is calculated in?", a: "Case control study", options: ["Cohort", "Case control study", "RCT", "Survey"] },
        { q: "Bias due to hospital admission rates?", a: "Berkson's bias", options: ["Recall bias", "Berkson's bias", "Interviewer bias", "Confounding"] },
        { q: "Confounding can be controlled by?", a: "Matching / Randomization", options: ["Blinding", "Matching / Randomization", "Increasing sample size", "None"] },
        { q: "Blinding removes?", a: "Observer / Subject bias", options: ["Confounding", "Selection bias", "Observer / Subject bias", "Berkson bias"] },
        { q: "Correlation coefficient ranges from?", a: "-1 to +1", options: ["0 to 1", "-1 to +1", "0 to 100", "-infinity to +infinity"] },
        { q: "Chi-square test is used for?", a: "Qualitative data (Proportions)", options: ["Quantitative data", "Qualitative data (Proportions)", "Mean comparison", "Correlation"] },
        { q: "T-test is used for?", a: "Comparing means of 2 groups", options: ["Proportions", "Comparing means of 2 groups", "3 or more groups", "Association"] },
        { q: "ANOVA is used for?", a: "Comparing means of >2 groups", options: ["2 groups", "Comparing means of >2 groups", "Proportions", "Medians"] },
        { q: "Normal distribution curve shape?", a: "Bell shaped / Symmetrical", options: ["Skewed", "Bell shaped / Symmetrical", "U shaped", "Flat"] },
        { q: "Mean, Median, Mode relationship in normal distribution?", a: "Mean = Median = Mode", options: ["Mean > Median", "Mean < Median", "Mean = Median = Mode", "Variable"] },
        { q: "Standard deviation covers?", a: "68% (1 SD), 95% (2 SD), 99.7% (3 SD)", options: ["50%", "68% (1 SD), 95% (2 SD), 99.7% (3 SD)", "90%", "100%"] },
        { q: "Incubation period of Measles?", a: "10-14 days", options: ["2-3 days", "10-14 days", "21 days", "1 month"] },
        { q: "Incubation period of Chickenpox?", a: "14-16 days", options: ["1 week", "14-16 days", "3 weeks", "2 days"] },
        { q: "Secondary attack rate measures?", a: "Communicability", options: ["Virulence", "Communicability", "Pathogenicity", "Incidence"] },
        { q: "ASHA worker population coverage?", a: "1000 (Rural)", options: ["500", "1000 (Rural)", "2500", "5000"] },
        { q: "Anganwadi worker population coverage?", a: "1000", options: ["500", "1000", "2000", "3000"] },
        { q: "Subcenter population coverage (Plain)?", a: "5000", options: ["3000", "5000", "10000", "20000"] },
        { q: "PHC population coverage (Plain)?", a: "30000", options: ["20000", "30000", "50000", "100000"] },
        { q: "CHC population coverage (Plain)?", a: "120000", options: ["80000", "120000", "50000", "10000"] },
        { q: "First Referral Unit (FRU)?", a: "CHC", options: ["PHC", "Subcenter", "CHC", "District Hospital"] },
        { q: "DOTS is for?", a: "Tuberculosis", options: ["Leprosy", "Tuberculosis", "Malaria", "HIV"] },
        { q: "MD Rh coverage?", a: "Leprosy", options: ["TB", "Leprosy", "Filariasis", "Kala-azar"] },
        // ... (Adding remaining questions to reach 150)
        { q: "Janani Suraksha Yojana (JSY) is a?", a: "Conditional cash transfer scheme", options: ["Insurance scheme", "Conditional cash transfer scheme", "Immunization program", "Nutritional program"] },
        { q: "ASHA is chosen by?", a: "Village Panchayat / Gram Sabha", options: ["MO", "ANM", "Village Panchayat / Gram Sabha", "District Magistrate"] },
        { q: "Village Health Guide scheme launched in?", a: "1977", options: ["1977", "1985", "2005", "1952"] },
        { q: "IMR of India (recent approximate)?", a: "28 per 1000 live births", options: ["10", "28 per 1000 live births", "50", "40"] },
        { q: "MMR of India (recent approximate)?", a: "97 per 1 lakh live births", options: ["200", "97 per 1 lakh live births", "150", "50"] },
        { q: "Current NMR of India?", a: "20 per 1000 live births", options: ["20 per 1000 live births", "30", "10", "40"] },
        { q: "Sustainable Development Goal (SDG) 3 is?", a: "Good Health and Well-being", options: ["No Poverty", "Good Health and Well-being", "Quality Education", "Clean Water"] },
        { q: "Target year for achieving SDGs?", a: "2030", options: ["2025", "2030", "2050", "2020"] },
        { q: "Which Committee is known as 'Health Survey and Development Committee'?", a: "Bhore Committee", options: ["Mudaliar", "Bhore Committee", "Srivastava", "Kartar Singh"] },
        { q: "Mudaliar Committee is known as?", a: "Health Survey and Planning Committee", options: ["Health Survey and Development", "Health Survey and Planning Committee", "Multipurpose Worker", "Medical Education"] },
        { q: "Kartar Singh Committee recommended?", a: "Multipurpose Workers (MPW)", options: ["3-tier structure", "Multipurpose Workers (MPW)", "ROME scheme", "Integration of health services"] },
        { q: "Srivastava Committee recommended?", a: "ROME scheme (Reorientation of Medical Education)", options: ["MPW", "ROME scheme", "Urban health", "School health"] },
        { q: "Alma-Ata Declaration (1978) is for?", a: "Primary Health Care", options: ["Health for All", "Primary Health Care", "Millennium Development Goals", "Sustainable Development"] },
        { q: "Elements of Primary Health Care?", a: "8", options: ["4", "8", "10", "12"] },
        { q: "Principles of Primary Health Care include all EXCEPT?", a: "Centralized planning", options: ["Equitable distribution", "Community participation", "Intersectoral coordination", "Centralized planning"] },
        { q: "Health For All by 2000 was a target of?", a: "Alma-Ata Declaration", options: ["Bhore Committee", "Alma-Ata Declaration", "MDGs", "SDGs"] },
        { q: "National Health Policy 2017 target for life expectancy?", a: "70 years by 2025", options: ["65 years", "70 years by 2025", "75 years", "80 years"] },
        { q: "NHP 2017 target for IMR?", a: "28 by 2019", options: ["28 by 2019", "20 by 2020", "15 by 2025", "10 by 2030"] },
        { q: "NHP 2017 target for TB elimination?", a: "2025", options: ["2030", "2025", "2020", "2035"] },
        { q: "Mission Indradhanush is related to?", a: "Immunization", options: ["Banking", "Immunization", "Sanitation", "Nutrition"] },
        { q: "Intensified Mission Indradhanush (IMI) targets?", a: "Drop-outs and left-outs (<2 years & pregnant women)", options: ["Elderly", "Drop-outs and left-outs", "Adolescents", "School children"] },
        { q: "Poshan Abhiyaan targets?", a: "Stunting, Undernutrition, Anemia, LBW", options: ["Obesity", "Stunting, Undernutrition, Anemia, LBW", "Infectious diseases", "Mental health"] },
        { q: "Ayushman Bharat scheme has two components:", a: "HWCs and PM-JAY", options: ["PHC and CHC", "HWCs and PM-JAY", "ICDS and RCH", "NRHM and NUHM"] },
        { q: "PM-JAY provides health cover of?", a: "Rs. 5 lakh per family per year", options: ["Rs. 1 lakh", "Rs. 2 lakh", "Rs. 5 lakh per family per year", "Rs. 10 lakh"] },
        { q: "Subcenters are being transformed into?", a: "Health and Wellness Centers (HWCs)", options: ["PHCs", "Health and Wellness Centers (HWCs)", "Dispensaries", "Polyclinics"] },
        { q: "Population covered by Urban PHC?", a: "50,000", options: ["30,000", "50,000", "100,000", "10,000"] },
        { q: "Who is the secretary of Village Health Sanitation and Nutrition Committee (VHSNC)?", a: "ASHA", options: ["ANM", "Anganwadi Worker", "ASHA", "Sarpanch"] },
        { q: "Rogi Kalyan Samiti (RKS) is at which level?", a: "PHC / CHC / DH", options: ["Subcenter", "PHC / CHC / DH", "Village", "State"] },
        { q: "Most common occupational cancer?", a: "Skin cancer", options: ["Lung cancer", "Skin cancer", "Bladder cancer", "Leukemia"] },
        { q: "Occupational cancer in dye industry?", a: "Bladder cancer", options: ["Lung", "Bladder cancer", "Skin", "Liver"] },
        { q: "Occupational hazard in asbestos industry?", a: "Mesothelioma / Asbestosis", options: ["Silicosis", "Mesothelioma / Asbestosis", "Byssinosis", "Bagassosis"] },
        { q: "Byssinosis is caused by?", a: "Cotton dust", options: ["Sugarcane dust", "Cotton dust", "Coal dust", "Silica"] },
        { q: "Bagassosis is caused by?", a: "Sugarcane dust", options: ["Cotton", "Sugarcane dust", "Tobacco", "Grain"] },
        { q: "Farmer's lung is caused by?", a: "Moldy hay (Micropolyspora faeni)", options: ["Cotton", "Moldy hay", "Silica", "Asbestos"] },
        { q: "Silicosis characteristic X-ray finding?", a: "Snowstorm appearance / Egg shell calcification", options: ["Ground glass", "Snowstorm / Egg shell", "Honeycomb", "Consolidation"] },
        { q: "Anthracosis is caused by?", a: "Coal dust", options: ["Iron", "Coal dust", "Silica", "Asbestos"] },
        { q: "Notifiable diseases under Factories Act?", a: "29", options: ["10", "20", "29", "50"] },
        { q: "ESI Act was passed in?", a: "1948", options: ["1948", "1952", "1975", "2000"] },
        { q: "Sickness benefit under ESI is for?", a: "91 days", options: ["56 days", "91 days", "1 year", "2 years"] },
        { q: "Maternity benefit under ESI is for?", a: "26 weeks", options: ["12 weeks", "26 weeks", "20 weeks", "1 year"] },
        { q: "Dependents benefit under ESI is?", a: "90% of wages", options: ["50%", "75%", "90% of wages", "100%"] },
        { q: "Biomedical waste management rule 2016 categories?", a: "4 (Yellow, Red, White, Blue)", options: ["10", "4 (Yellow, Red, White, Blue)", "5", "3"] },
        { q: "Incineration is best for?", a: "Anatomical waste (Human/Animal)", options: ["Plastic", "Glass", "Anatomical waste", "Sharps"] },
        { q: "Plastic waste (IV bottles, syringes without needles) goes in?", a: "Red bag", options: ["Yellow", "Red bag", "Blue", "White"] },
        { q: "Sharps (Needles, Scalpels) go in?", a: "White translucent puncture proof container", options: ["Red", "Yellow", "White translucent", "Blue"] },
        { q: "Broken glass goes in?", a: "Blue bag", options: ["Red", "Yellow", "White", "Blue bag"] },
        { q: "Cytotoxic drugs disposal?", a: "Yellow bag (Incineration > 1200C)", options: ["Red", "Yellow bag", "Blue", "Black"] },
        { q: "Discarded medicines disposal?", a: "Yellow bag", options: ["Red", "Yellow bag", "Blue", "White"] },
        { q: "Blood bags disposal?", a: "Yellow bag", options: ["Red", "Yellow bag", "Blue", "White"] },
        { q: "Liquid waste treatment?", a: "Chemical treatment (Hypochlorite) then drain", options: ["Incineration", "Chemical treatment then drain", "Autoclave", "Deep burial"] },
        { q: "Ergonomics is?", a: "Fitting the job to the worker", options: ["Fitting worker to job", "Fitting the job to the worker", "Machine safety", "Environment protection"] },
        { q: "Lead poisoning indicator?", a: "Urine ALA / Blood Lead / CPU", options: ["Urine sugar", "Urine ALA / Blood Lead", "Serum Creatinine", "Liver enzymes"] },
        { q: "Minamata disease is caused by?", a: "Methyl Mercury", options: ["Lead", "Methyl Mercury", "Cadmium", "Arsenic"] },
        { q: "Itai-Itai disease is caused by?", a: "Cadmium", options: ["Lead", "Mercury", "Cadmium", "Arsenic"] },
        { q: "Blackfoot disease is caused by?", a: "Arsenic", options: ["Lead", "Mercury", "Cadmium", "Arsenic"] },
        { q: "Goiter belt in India?", a: "Himalayan region", options: ["Coastal", "Himalayan region", "Plains", "Desert"] },
        { q: "Endemic fluorosis is common in?", a: "Andhra Pradesh / Rajasthan / Punjab", options: ["Kerala", "Andhra Pradesh / Rajasthan", "Goa", "Assam"] },
        { q: "Screening test for Breast Cancer?", a: "Mammography", options: ["USG", "Mammography", "Self exam", "MRI"] },
        { q: "Screening test for Cervical Cancer?", a: "Pap smear / VIA", options: ["Colposcopy", "Pap smear / VIA", "Biopsy", "USG"] },
        { q: "Most common cause of ID in India?", a: "Tuberculosis", options: ["Malaria", "Tuberculosis", "HIV", "Dengue"] }, // Generalized.
        { q: "Vector of Lymphatic Filariasis?", a: "Culex quinquefasciatus", options: ["Anopheles", "Culex quinquefasciatus", "Aedes", "Mansonia"] },
        { q: "Mass Drug Administration (MDA) for Filariasis drugs?", a: "DEC + Albendazole (+ Ivermectin)", options: ["Chloroquine", "DEC + Albendazole", "Penicillin", "Doxycycline"] },
        { q: "Endemic Treponematoses?", a: "Yaws", options: ["Syphilis", "Yaws", "Gonorrhea", "Chancroid"] },
        { q: "Yaws eradication strategy?", a: "Total Mass Treatment (TMT)", options: ["Vector control", "Total Mass Treatment (TMT)", "Vaccination", "Isolation"] },
        { q: "Leprosy elimination target?", a: "< 1 case per 10,000 population", options: ["Zero cases", "< 1 case per 10,000 population", "< 5 per 10,000", "< 10 per 10,000"] },
        { q: "Paucibacillary Leprosy treatment duration?", a: "6 months", options: ["12 months", "6 months", "18 months", "24 months"] },
        { q: "Multibacillary Leprosy treatment duration?", a: "12 months", options: ["6 months", "12 months", "18 months", "24 months"] },
        { q: "Drugs in PB Leprosy pack?", a: "Rifampicin + Dapsone", options: ["Rifampicin + Clofazimine", "Rifampicin + Dapsone", "Dapsone + Clofazimine", "All three"] },
        { q: "Drugs in MB Leprosy pack?", a: "Rifampicin + Dapsone + Clofazimine", options: ["Rifampicin + Dapsone", "Rifampicin + Dapsone + Clofazimine", "Oflaxacin", "Minocycline"] },
        { q: "Kala-azar vector control?", a: "DDT spray", options: ["Malathion", "DDT spray", "Fogging", "Larvicides"] },
        { q: "National Vector Borne Disease Control Program (NVBDCP) covers how many diseases?", a: "6 (Malaria, Filaria, Kala-azar, JE, Dengue, Chikungunya)", options: ["4", "5", "6", "8"] },
        { q: "RNTCP is now known as?", a: "NTEP (National Tuberculosis Elimination Program)", options: ["RNTCP II", "NTEP", "NTCP", "TB Free India"] },
        { q: "Nikshay Poshan Yojana provides?", a: "Rs. 500 per month to TB patients", options: ["Rs. 1000", "Rs. 500 per month", "Food baskets", "Medicines only"] },
        { q: "CBNAAT detects?", a: "M. tuberculosis and Rifampicin resistance", options: ["Only TB", "M. tuberculosis and Rifampicin resistance", "Isoniazid resistance", "MDR TB"] },
        { q: "MDR TB is resistance to?", a: "Isoniazid and Rifampicin", options: ["Isoniazid only", "Rifampicin only", "Isoniazid and Rifampicin", "Fluoroquinolones"] },
        { q: "XDR TB is resistance to?", a: "MDR + Fluoroquinolone + Injectable SLD", options: ["MDR + Isoniazid", "MDR + Fluoroquinolone + Injectable SLD", "All drugs", "Rifampicin"] },
        { q: "Bedaquiline is used for?", a: "MDR/XDR TB", options: ["Sensitive TB", "MDR/XDR TB", "Leprosy", "Malaria"] },
        { q: "National AIDS Control Program (NACP) phase?", a: "Phase V (2021-2026)", options: ["III", "IV", "Phase V", "VI"] },
        { q: "95-95-95 strategy is for?", a: "HIV/AIDS", options: ["TB", "HIV/AIDS", "Malaria", "Leprosy"] },
        { q: "Screening test for HIV?", a: "ELISA / Rapid tests (Antibody)", options: ["Western Blot", "ELISA / Rapid tests", "PCR", "Culture"] },
        { q: "Confirmatory test for HIV?", a: "Western Blot (Previously) / 3 different principles", options: ["ELISA", "Western Blot / 3 principles", "VDRL", "Widal"] },
        { q: "Window period for HIV?", a: "Up to 3 months (Antibodies)", options: ["1 week", "Up to 3 months", "6 months", "1 year"] },
        { q: "Post Exposure Prophylaxis (PEP) for HIV best started within?", a: "2 hours (Max 72 hours)", options: ["24 hours", "2 hours (Max 72 hours)", "1 week", "Is useless"] },
        { q: "PEP duration?", a: "28 days", options: ["7 days", "14 days", "28 days", "6 months"] },
        { q: "Regimen for PEP?", a: "Tenofovir + Lamivudine + Dolutegravir", options: ["Zidovudine", "Tenofovir + Lamivudine + Dolutegravir", "Nevirapine", "Efavirenz"] },
        { q: "Prevention of Parent to Child Transmission (PPTCT) regimen?", a: "Lifelong ART for mother (Option B+)", options: ["Single dose Nevirapine", "Lifelong ART for mother", "Zidovudine only", "None"] },
        { q: "Most common route of HIV transmission in India?", a: "Heterosexual", options: ["Homosexual", "Heterosexual", "IV drug use", "Blood transfusion"] },
        { q: "Route with highest efficiency of HIV transmission?", a: "Blood transfusion", options: ["Sexual", "Blood transfusion", "Needle stick", "Mother to child"] },
        { q: "Integrated Disease Surveillance Program (IDSP) forms?", a: "S (Suspect), P (Presumptive), L (Lab confirmed)", options: ["A, B, C", "S, P, L", "1, 2, 3", "X, Y, Z"] },
        { q: "Form S is filled by?", a: "Health workers (ANM)", options: ["Doctors", "Health workers (ANM)", "Lab tech", "Public"] },
        { q: "Form P is filled by?", a: "Doctors", options: ["ANM", "Doctors", "Lab tech", "Pharmacist"] },
        { q: "Form L is filled by?", a: "Lab technicians", options: ["Doctors", "ANM", "Lab technicians", "Epidemiologist"] },
        { q: "Cold Chain temperature for most vaccines?", a: "+2 to +8 degrees Celsius", options: ["-20 C", "+2 to +8 degrees Celsius", "Room temp", "0 C"] },
        { q: "Vaccines stored in freezer compartment?", a: "OPV, Measles", options: ["DPT, TT", "OPV, Measles", "Hep B", "Pentavalent"] },
        { q: "Vaccines damaged by freezing (Freeze sensitive)?", a: "Hep B, DPT, TT, IPV", options: ["OPV", "Measles", "Hep B, DPT, TT, IPV", "BCG"] },
        { q: "Most heat sensitive vaccine?", a: "OPV (Reconstituted BCG/Measles even more)", options: ["TT", "Hep B", "OPV", "DPT"] }, // OPV usually cited. Reconstituted ones are very labile.
        { q: "Most heat resistant vaccine?", a: "TT", options: ["OPV", "Measles", "TT", "BCG"] },
        { q: "Shake test is used for?", a: "Checking if freeze-sensitive vaccine is damaged", options: ["Potency", "Checking if freeze-sensitive vaccine is damaged", "Contamination", "Expiry"] },
        { q: "Open Vial Policy applies to?", a: "DPT, TT, Hep B, OPV, IPV, Pentavalent (Liquid)", options: ["Measles, BCG", "DPT, TT, Hep B, OPV, IPV", "Rotavirus", "JE"] },
        { q: "Reconstituted vaccines (BCG, Measles, JE) must be used within?", a: "4 hours", options: ["1 hour", "4 hours", "24 hours", "1 week"] },
        { q: "Ice lined refrigerator (ILR) maintains temp for?", a: "District / PHC level", options: ["Regional", "District / PHC level", "Subcenter", "Home"] },
        { q: "Diluent for BCG?", a: "Normal Saline", options: ["Distilled water", "Normal Saline", "Dextrose", "Ringer Lactate"] },
        { q: "Diluent for Measles?", a: "Distilled Water", options: ["Normal Saline", "Distilled Water", "Buffer", "Oil"] },
        { q: "Adjuvant used in DPT?", a: "Aluminium phosphate / hydroxide", options: ["Oil", "Aluminium phosphate / hydroxide", "Mercury", "Water"] },
        { q: "Preservative in multi-dose vials?", a: "Thiomersal", options: ["Phenol", "Thiomersal", "Formalin", "Alcohol"] },
        { q: "Incubation period of Rabies?", a: "3-8 weeks (highly variable)", options: ["1-2 days", "3-8 weeks", "1 year", "10 days"] },
        { q: "Category III dog bite includes?", a: "Single/multiple transdermal bites or scratches, licks on broken skin", options: ["Licks on intact skin", "Minor scratches without bleeding", "Single/multiple transdermal bites or scratches", "Touching"] },
        { q: "Treatment for Category III bite?", a: "Wound wash + Vaccine + Immunoglobulin (RIG)", options: ["Vaccine only", "Wound wash + Vaccine + RIG", "Observation", "Antibiotics"] },
        { q: "Route of Rabies vaccine (ID)?", a: "0.1 ml at 2 sites on days 0, 3, 7, 28", options: ["IM", "0.1 ml at 2 sites on days 0, 3, 7, 28", "Oral", "Subcut"] },
        { q: "Site for IM rabies vaccine?", a: "Deltoid (Adults), Anterolateral thigh (Children)", options: ["Gluteal", "Deltoid / Thigh", "Abdomen", "Forearm"] },
        { q: "Intradermal Rabies regimen name?", a: "Updated Thai Red Cross regimen (2-2-2-0-2)", options: ["Essen", "Zagreb", "Updated Thai Red Cross", "Pasteur"] },
        { q: "Dose of Equine Rabies Immunoglobulin (ERIG)?", a: "40 IU/kg", options: ["20 IU/kg", "40 IU/kg", "10 IU/kg", "100 IU/kg"] },
        { q: "Dose of Human Rabies Immunoglobulin (HRIG)?", a: "20 IU/kg", options: ["40 IU/kg", "20 IU/kg", "10 IU/kg", "5 IU/kg"] },
        { q: "Observational period for dog after bite?", a: "10 days", options: ["5 days", "10 days", "14 days", "1 month"] },
        { q: "Milk pasteurization Holder's method?", a: "63°C for 30 mins", options: ["72°C for 15 sec", "63°C for 30 mins", "100°C for 1 sec", "130°C for 1 sec"] },
        { q: "Milk pasteurization HTST method?", a: "72°C for 15 seconds", options: ["63°C for 30 mins", "72°C for 15 seconds", "100°C", "UHT"] },
        { q: "Test for pasteurization efficiency?", a: "Phosphatase test", options: ["Methylene blue", "Phosphatase test", "Turbidity", "Coliform count"] },
        { q: "Refuse to be disposed distance from well?", a: "15 meters (50 feet)", options: ["5 meters", "15 meters", "50 meters", "100 meters"] },
        { q: "Most accurate method of population census?", a: "De facto", options: ["De jure", "De facto", "Sample", "Vital registration"] },
        { q: "Census in India is done every?", a: "10 years", options: ["5 years", "10 years", "1 year", "20 years"] },
        { q: "Sex ratio is?", a: "Females per 1000 Males", options: ["Males per 1000 Females", "Females per 1000 Males", "Females per 100", "Males per 100"] },
        { q: "Dependency ratio formula?", a: "(0-14 + >65) / (15-64) * 100", options: ["(15-64) / (0-14)", "(0-14 + >65) / (15-64) * 100", "Total / Working", "Working / Total"] },
        { q: "Demographic gap is difference between?", a: "Birth rate and Death rate", options: ["IMR and MMR", "Birth rate and Death rate", "Immigration and Emigration", "None"] },
        { q: "Stage of demographic cycle of India?", a: "Late Expanding (Stage 3)", options: ["High Stationary", "Early Expanding", "Late Expanding", "Low Stationary"] },
        { q: "Checking accuracy of screening test?", a: "Validity", options: ["Reliability", "Validity", "Precision", "Repeatability"] },
        { q: "Repeatability of a test?", a: "Reliability", options: ["Validity", "Reliability", "Accuracy", "Sensitivity"] },
        { q: "Hard tick transmits?", a: "KFD, Tick typhus, Babesiosis", options: ["Relapsing fever", "KFD, Tick typhus", "Plague", "Scabies"] },
        { q: "Soft tick transmits?", a: "Relapsing fever, Q fever", options: ["KFD", "Relapsing fever", "Lyme disease", "Typhus"] },
        { q: "Trombiculid mite transmits?", a: "Scrub typhus", options: ["Scabies", "Scrub typhus", "Rickettsialpox", "Plague"] },
        { q: "Itch mite causes?", a: "Scabies", options: ["Scrub typhus", "Scabies", "Pediculosis", "Kala-azar"] },
        { q: "Louse transmits?", a: "Epidemic typhus, Relapsing fever, Trench fever", options: ["Endemic typhus", "Epidemic typhus, Relapsing fever, Trench fever", "Plague", "Dengue"] },
        { q: "Cyclops transmits?", a: "Dracunculiasis (Guinea worm), Fish tapeworm", options: ["Malaria", "Dracunculiasis, Fish tapeworm", "Filaria", "Schistosomiasis"] },
        { q: "Hypertension rule of halves?", a: "Half known, Half treated, Half controlled", options: ["All treated", "Half known, Half treated, Half controlled", "None known", "Full control"] },
        { q: "Tracking system for pregnant women and children?", a: "RCH Portal / MCP Card", options: ["Aadhar", "RCH Portal / MCP Card", "Bank account", "Voter ID"] }
    ]);
}
