// FMGE Ultimate Revision - Psychiatry Module
// Source: MIST PSYCHIATRY SUBJECT WISE TEST (9th Nov 2025)

if (typeof window.registerSubject === 'function') {
    window.registerSubject('Psychiatry', [
        { q: "A 72-year-old woman in burn unit pulls out IV, screams people are hurting her, disoriented. Diagnosis?", a: "Delirium", options: ["Dementia", "Brief reactive psychosis", "Acute manic episode", "Delirium"] },
        { q: "18M mumbles to self, stops answer in middle of sentence (forgot what to say). Symptom?", a: "Blocking", options: ["Incongruent affect", "Blocking", "Perseveration", "Tangentiality"] },
        { q: "Patient convinced she caused earthquake because she was bored. Symptom?", a: "Magical thinking", options: ["Thought broadcasting", "Magical thinking", "Delusion of reference", "Grandiosity"] },
        { q: "After a traumatic event, patient has nightmares, flashbacks, and avoidance for >1 month. Diagnosis?", a: "Post-traumatic stress disorder", options: ["Acute stress disorder", "Generalized anxiety disorder", "Major depressive disorder", "Post-traumatic stress disorder"] },
        { q: "Symptoms of PTSD lasting < 1 month is called?", a: "Acute Stress Disorder", options: ["PTSD", "Acute Stress Disorder", "Adjustment Disorder", "Panic Disorder"] },
        { q: "Treatment of choice for Bipolar Disorder?", a: "Lithium", options: ["Lithium", "Diazepam", "Fluoxetine", "Haloperidol"] },
        { q: "Side effect of Lithium?", a: "Tremors / Hypothyroidism / Polyuria", options: ["Sedation", "Tremors / Hypothyroidism", "Hypertension", "Weight loss"] },
        { q: "Therapeutic range of Lithium?", a: "0.6 - 1.2 mEq/L", options: ["0.2 - 0.5", "0.6 - 1.2", "1.5 - 2.0", "2.0 - 3.0"] },
        { q: "Alcohol withdrawal delirium (Delirium Tremens) occurs when?", a: "48-72 hours after cessation", options: ["6-12 hours", "12-24 hours", "48-72 hours", "1 week"] },
        { q: "Drug of choice for alcohol withdrawal?", a: "Benzodiazepines (Chlordiazepoxide)", options: ["Disulfiram", "Acamprosate", "Benzodiazepines", "Naltrexone"] },
        { q: "Wernicke's Encephalopathy triad includes confusion, ataxia, and?", a: "Ophthalmoplegia", options: ["Ophthalmoplegia", "Seizures", "Diarrhea", "Dermatitis"] },
        { q: "Confabulation is seen in?", a: "Korsakoff's psychosis", options: ["Wernicke's encephalopathy", "Korsakoff's psychosis", "Delirium tremens", "Alcohol intoxication"] },
        { q: "Fear of open spaces is called?", a: "Agoraphobia", options: ["Claustrophobia", "Agoraphobia", "Acrophobia", "Xenophobia"] },
        { q: "False sensory perception without external stimulus?", a: "Hallucination", options: ["Illusion", "Hallucination", "Delusion", "Idea of reference"] },
        { q: "False sensory perception WITH external stimulus (misinterpretation)?", a: "Illusion", options: ["Hallucination", "Illusion", "Delusion", "Obsession"] },
        { q: "Fixed false belief not amenable to reasoning?", a: "Delusion", options: ["Hallucination", "Illusion", "Delusion", "Obsession"] },
        { q: "Key feature of Anorexia Nervosa?", a: "Body image distortion / Refusal to maintain weight", options: ["Binge eating", "Body image distortion", "Normal weight", "Menorrhagia"] },
        { q: "Russell's sign (calluses on knuckles) is seen in?", a: "Bulimia Nervosa", options: ["Anorexia Nervosa", "Bulimia Nervosa", "Binge Eating Disorder", "Pica"] },
        { q: "Treatment of choice for OCD?", a: "SSRI + CBT (Exposure and Response Prevention)", options: ["Benzodiazepines", "SSRI + CBT", "Antipsychotics", "ECT"] },
        { q: "Flight of ideas is a feature of?", a: "Mania", options: ["Depression", "Mania", "Schizophrenia", "OCD"] },
        { q: "Anhedonia (lack of pleasure) is a core symptom of?", a: "Depression", options: ["Mania", "Depression", "Anxiety", "Delirium"] },
        { q: "Drug of choice for Depression?", a: "SSRI", options: ["TCA", "MAO Inhibitors", "SSRI", "Benzodiazepines"] },
        { q: "Example of SSRI?", a: "Fluoxetine / Escitalopram / Sertraline", options: ["Amitriptyline", "Fluoxetine", "Venlafaxine", "Diazepam"] },
        { q: "Mechanism of action of SSRI?", a: "Inhibit reuptake of Serotonin", options: ["Block Dopamine", "Inhibit reuptake of Serotonin", "Increase GABA", "Block Histamine"] },
        { q: "Schizophrenia symptom duration criteria?", a: "> 6 months", options: ["< 1 month", "1-6 months", "> 6 months", "2 weeks"] },
        { q: "Brief Psychotic Disorder duration?", a: "< 1 month", options: ["< 1 month", "1-6 months", "> 6 months", "1 day"] },
        { q: "Schizophreniform Disorder duration?", a: "1-6 months", options: ["< 1 month", "1-6 months", "> 6 months", "2 years"] },
        { q: "Negative symptoms of Schizophrenia include?", a: "Apathy, Avolition, Alogia, Anhedonia", options: ["Hallucinations, Delusions", "Apathy, Avolition, Alogia", "Flight of ideas", "Obsessions"] },
        { q: "Drug of choice for treatment resistant Schizophrenia?", a: "Clozapine", options: ["Haloperidol", "Risperidone", "Clozapine", "Olanzapine"] },
        { q: "Side effect of Clozapine?", a: "Agranulocytosis / Sialorrhea", options: ["Extrapyramidal symptoms", "Agranulocytosis / Sialorrhea", "Hyperprolactinemia", "Insomnia"] },
        { q: "Neuroleptic Malignant Syndrome features?", a: "Rigidity, Hyperthermia, Autonomic instability", options: ["Tremor, confusion, diarrhea", "Rigidity, Hyperthermia, Autonomic instability", "Seizures, coma", "Hypertension only"] },
        { q: "Treatment of Neuroleptic Malignant Syndrome?", a: "Dantrolene / Bromocriptine", options: ["Atropine", "Dantrolene", "Propranolol", "Succinylcholine"] },
        { q: "Most common side effect of ECT?", a: "Retrograde Amnesia", options: ["Fracture", "Retrograde Amnesia", "Arrhythmia", "Headache"] },
        { q: "IQ range for Mild Mental Retardation?", a: "50-70", options: ["50-70", "35-50", "20-35", "<20"] },
        { q: "IQ range for Moderate Mental Retardation?", a: "35-50", options: ["50-70", "35-50", "20-35", "<20"] },
        { q: "Condition characterized by motor and vocal tics?", a: "Tourette's Syndrome", options: ["ADHD", "Tourette's Syndrome", "Autism", "OCD"] },
        { q: "Core features of ADHD?", a: "Inattention, Hyperactivity, Impulsivity", options: ["Social withdrawal", "Inattention, Hyperactivity, Impulsivity", "Low IQ", "Aggression"] },
        { q: "Drug of choice for ADHD?", a: "Methylphenidate", options: ["Atomoxetine", "Methylphenidate", "Clonidine", "Fluoxetine"] },
        { q: "Condition with deficits in social communication and repetitive behaviors?", a: "Autism Spectrum Disorder", options: ["ADHD", "Autism Spectrum Disorder", "Mental Retardation", "Conduct Disorder"] },
        { q: "Factitious Disorder is?", a: "Intentionally producing symptoms for sick role", options: ["External gain (Malingering)", "Intentionally producing symptoms for sick role", "Unconscious symptoms (Conversion)", "Fear of illness"] },
        { q: "Malingering is?", a: "Intentionally producing symptoms for external gain", options: ["Sick role", "External gain", "Unconscious", "Anxiety"] },
        { q: "Conversion Disorder is?", a: "Neurological symptoms incompatible with anatomy (Unconscious)", options: ["Conscious feigning", "Neurological symptoms incompatible with anatomy", "Fear of illness", "Obsession"] },
        { q: "Narcolepsy tetrad?", a: "Sleep attacks, Cataplexy, Hallucinations, Sleep Paralysis", options: ["Insomnia, Snoring", "Sleep attacks, Cataplexy, Hallucinations, Sleep Paralysis", "Sleep walking, terrors", "Apnea"] },
        { q: "Cataplexy is?", a: "Sudden loss of muscle tone triggered by emotion", options: ["Sleep attack", "Sudden loss of muscle tone triggered by emotion", "Paralysis on waking", "Hallucination"] },
        { q: "Disulfiram reaction mechanism?", a: "Inhibits Aldehyde Dehydrogenase", options: ["Inhibits Alcohol Dehydrogenase", "Inhibits Aldehyde Dehydrogenase", "Blocks Opioid receptor", "Stimulates GABA"] },
        { q: "Erotomania (De Clerambault's syndrome) is?", a: "Delusion that someone high status is in love with them", options: ["Jealousy", "Persecution", "Delusion that someone high status is in love with them", "Infidelity"] },
        { q: "Capgras syndrome is?", a: "Delusion of doubles (Imposter)", options: ["Fregoli", "Capgras", "Cotard", "Erotomania"] },
        { q: "Cotard's syndrome is?", a: "Nihilistic delusion (Dead/Non-existent)", options: ["Grandiosity", "Nihilistic delusion", "Persecution", "Reference"] },
        { q: "Fregoli syndrome is?", a: "Delusion that a persecutor takes on different faces", options: ["Doubles", "Fregoli", "Capgras", "Cotard"] },
        { q: "Most common suicide method in India?", a: "Poisoning (Pesticides) / Hanging", options: ["Firearm", "Poisoning / Hanging", "Drowning", "Jumping"] }
    ]);
}