if (typeof window.registerSubject === 'function') {
    window.registerSubject('Orthopedics', [
        { q: "30M, RTA. Right lower limb externally rotated, abducted, lengthened. Diagnosis?", a: "Anterior dislocation of hip", options: ["Fracture neck femur", "Posterior dislocation", "Central fracture dislocation", "Anterior dislocation of hip"] },
        { q: "Colles fracture is fracture of?", a: "Distal end of radius", options: ["Distal ulna", "Distal end of radius", "Scaphoid", "Humerus"] },
        { q: "Deformity seen in Colles fracture?", a: "Dinner fork deformity", options: ["Garden spade deformity", "Dinner fork deformity", "Swan neck deformity", "Boutonniere deformity"] },
        { q: "Smith's fracture deformity?", a: "Garden spade deformity", options: ["Dinner fork", "Garden spade deformity", "Mallet finger", "Claw hand"] },
        { q: "Monteggia fracture dislocation involves?", a: "Proximal Ulna fracture + Radial Head dislocation", options: ["Distal Radius + DRUJ", "Proximal Ulna fracture + Radial Head dislocation", "Radius shaft + Ulna dislocation", "Both bone forearm"] },
        { q: "Galeazzi fracture dislocation involves?", a: "Distal Radius fracture + DRUJ dislocation", options: ["Proximal Ulna + Radial head", "Distal Radius fracture + DRUJ dislocation", "Scaphoid fracture", "Humerus fracture"] },
        { q: "Most common carpal bone fractured?", a: "Scaphoid", options: ["Lunate", "Scaphoid", "Capitate", "Hamate"] },
        { q: "Most common carpal bone dislocated?", a: "Lunate", options: ["Scaphoid", "Lunate", "Trapezium", "Triquetrum"] },
        { q: "Boxer's fracture involves?", a: "5th Metacarpal neck", options: ["1st Metacarpal", "5th Metacarpal neck", "Scaphoid", "Distal Radius"] },
        { q: "Fat embolism syndrome classic triad?", a: "Hypoxemia, Neurological abnormalities, Petechial rash", options: ["Fever, Pain, Swelling", "Hypoxemia, Neurological abnormalities, Petechial rash", "Shock, Pallor, Pain", "None"] },
        { q: "Compartment syndrome earliest sign?", a: "Pain on passive stretch", options: ["Pulselessness", "Pallor", "Paralysis", "Pain on passive stretch"] },
        { q: "Treatment of Compartment Syndrome?", a: "Fasciotomy", options: ["Plaster cast", "Fasciotomy", "Traction", "Amputation"] },
        { q: "Osteosarcoma mostly affects?", a: "Metaphysis of long bones", options: ["Diaphysis", "Metaphysis of long bones", "Epiphysis", "Flat bones"] },
        { q: "Sunburst appearance / Codman's triangle is seen in?", a: "Osteosarcoma", options: ["Ewing's sarcoma", "Osteosarcoma", "GCT", "Chondrosarcoma"] },
        { q: "Ewing's Sarcoma mostly affects?", a: "Diaphysis", options: ["Epiphysis", "Metaphysis", "Diaphysis", "Spine"] },
        { q: "Onion peel appearance is seen in?", a: "Ewing's Sarcoma", options: ["Osteosarcoma", "Ewing's Sarcoma", "GCT", "Osteomyelitis"] },
        { q: "Giant Cell Tumor (Osteoclastoma) location?", a: "Epiphysis", options: ["Diaphysis", "Metaphysis", "Epiphysis", "Joint"] },
        { q: "Soap bubble appearance is seen in?", a: "Giant Cell Tumor", options: ["Osteosarcoma", "Giant Cell Tumor", "Bone Cyst", "Fibrous Dysplasia"] },
        { q: "Pott's Spine involves?", a: "Tuberculosis of Spine", options: ["Fracture spine", "Tuberculosis of Spine", "Scoliosis", "Tumor"] },
        { q: "Bamboo spine is characteristic of?", a: "Ankylosing Spondylitis", options: ["RA", "Ankylosing Spondylitis", "OA", "Disc prolapse"] },
        { q: "Trendelenburg sign is positive in?", a: "Dislocation of Hip / Gluteus Medius weakness", options: ["Knee injury", "Dislocation of Hip / Gluteus Medius weakness", "Ankle sprain", "Spine fracture"] },
        { q: "Lachman test is for?", a: "ACL tear", options: ["PCL", "ACL tear", "Meniscus", "MCL"] },
        { q: "McMurray test is for?", a: "Meniscal tear", options: ["ACL", "PCL", "Meniscal tear", "LCL"] },
        { q: "Posterior Drawer test is for?", a: "PCL tear", options: ["ACL", "PCL tear", "Meniscus", "Collateral ligament"] },
        { q: "Unhappy triad of knee?", a: "ACL, MCL, Medial Meniscus", options: ["PCL, LCL, Lateral meniscus", "ACL, MCL, Medial Meniscus", "ACL, LCL, Lateral Meniscus", "None"] },
        { q: "Myositis Ossificans is?", a: "Calcification in muscle after trauma", options: ["Infection of muscle", "Calcification in muscle after trauma", "Tumor of muscle", "Genetic disorder"] },
        { q: "Mallet finger is injury to?", a: "Extensor tendon at DIP", options: ["Flexor tendon", "Extensor tendon at DIP", "Collateral ligament", "Volar plate"] },
        { q: "Boutonniere deformity?", a: "Flexion at PIP, Extension at DIP", options: ["Extension at PIP, Flexion at DIP", "Flexion at PIP, Extension at DIP", "Flexion at both", "Extension at both"] },
        { q: "Swan neck deformity?", a: "Extension at PIP, Flexion at DIP", options: ["Flexion at PIP", "Extension at PIP, Flexion at DIP", "Mallet finger", "Claw hand"] },
        { q: "Tennis Elbow involves?", a: "Lateral Epicondyle (Extensor origin)", options: ["Medial Epicondyle", "Lateral Epicondyle (Extensor origin)", "Olecranon", "Radial head"] },
        { q: "Golfer's Elbow involves?", a: "Medial Epicondyle (Flexor origin)", options: ["Lateral Epicondyle", "Medial Epicondyle (Flexor origin)", "Bicipital groove", "Triceps insertion"] },
        { q: "Frozen shoulder is?", a: "Adhesive Capsulitis", options: ["Dislocation", "Adhesive Capsulitis", "Fracture", "Tendonitis"] },
        { q: "Saturday Night Palsy involves?", a: "Radial Nerve", options: ["Ulnar", "Median", "Radial Nerve", "Axillary"] },
        { q: "Erb's Palsy posture?", a: "Policeman's tip hand", options: ["Claw hand", "Policeman's tip hand", "Wrist drop", "Ape thumb"] },
        { q: "Klumpke's Palsy results in?", a: "Claw hand", options: ["Wrist drop", "Claw hand", "Foot drop", "Ape thumb"] },
        { q: "Foot drop is due to injury of?", a: "Common Peroneal Nerve", options: ["Tibial", "Common Peroneal Nerve", "Femoral", "Sciatic"] },
        { q: "Brodie's Abscess is?", a: "Chronic Osteomyelitis", options: ["Acute Osteomyelitis", "Chronic Osteomyelitis", "TB", "Tumor"] },
        { q: "Sequestrum is?", a: "Dead bone", options: ["New bone", "Dead bone", "Pus", "Fibrous tissue"] },
        { q: "Involucrum is?", a: "New bone formation around sequestrum", options: ["Dead bone", "New bone formation around sequestrum", "Sinus tract", "Abscess"] },
        { q: "Osteogenesis Imperfecta is defect in?", a: "Type 1 Collagen", options: ["Type 2 Collagen", "Type 1 Collagen", "Fibrillin", "Elastin"] },
        { q: "Blue Sclera is seen in?", a: "Osteogenesis Imperfecta", options: ["Osteopetrosis", "Osteogenesis Imperfecta", "Achondroplasia", "Rickets"] },
        { q: "Achondroplasia is?", a: "Autosomal Dominant", options: ["AR", "Autosomal Dominant", "XR", "Mitochondrial"] },
        { q: "Marble bone disease is?", a: "Osteopetrosis", options: ["Osteoporosis", "Osteopetrosis", "Osteomalacia", "Paget's"] },
        { q: "Rickets X-ray features?", a: "Cupping, Fraying, Splaying", options: ["Sclerosis", "Cupping, Fraying, Splaying", "Periosteal reaction", "Lytic lesions"] },
        { q: "Scurvy X-ray features?", a: "White line of Frankel, Wimberger's ring", options: ["Looser's zones", "White line of Frankel, Wimberger's ring", "Codman's triangle", "Onion peel"] },
        { q: "Brown tumor is seen in?", a: "Hyperparathyroidism", options: ["Hypoparathyroidism", "Hyperparathyroidism", "Rickets", "Osteoporosis"] },
        { q: "Most common site of bone TB?", a: "Spine", options: ["Hip", "Knee", "Spine", "Ankle"] },
        { q: "Jefferson fracture involves?", a: "Atlas (C1)", options: ["Axis (C2)", "Atlas (C1)", "C3", "C7"] },
        { q: "Hangman's fracture involves?", a: "Axis (C2)", options: ["Atlas", "Axis (C2)", "C5", "C6"] },
        { q: "Clay shoveler's fracture involves?", a: "Spinous process of C7/T1", options: ["Body of C2", "Spinous process of C7/T1", "Transverse process", "Odontoid"] }
    ]);
}